### ISSUE TITLE
Quick smooth shortcut.

### ISSUE THREAD

**Issue by ettiSurreal** [TokisanGames/Terrain3D#123]
When a key is held down (Shift should be familiar to Blender users), the current tool is temporarily switched to the smooth brush, and goes back to the previous tool when let go.
Additionally, whenever https://github.com/outobugi/Terrain3D/issues/102 is implemented, holding down Shift and CTRL at the same time, it should switch to the erosion brush, as the inverse of smoothing is sharpening, and erosion would be the closest to it.

**Comment by Calinou** [comment]
See my suggestion here: https://github.com/outobugi/Terrain3D/issues/122#issuecomment-1641019108

**Comment by TokisanGames** [comment]
Let's consolidate this ticket into #122
