### ISSUE TITLE
Add a channel packing tool

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#125]
Channel packing is a pita. We should accept the individual pbr files and channel pack them ourselves or add a tool that channel packs images.

However, we need to make sure this load on an exported game as Godot may only export it's cached dds conversions.

**Comment by outobugi** [comment]
The textures _had_ separate slots in the surface resource and packing happened when TextureArray was created. This had massive performance issues. First I had to uncompress all textures, move e.g roughness to alpha channel pixel by pixel and then compress again. All slow processes. And this would happen every time a new texture was added.

What I think would be the best solution is a custom importer. It would combine albedo/normal map, with a specified height/roughness map and compress it correctly.

**Comment by TokisanGames** [comment]
We need a tools menu that handles importing and exporting maps. It can also do channel packing file creation. Basically incorporating Zylann's channel packer tool.

**Comment by outobugi** [comment]
> We need a tools menu that handles importing and exporting maps. It can also do channel packing file creation. Basically incorporating Zylann's channel packer tool.

Honestly, I never liked Zylann's packer tool. For easiest and fastest workflow the importer is a must.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/2316.

**Comment by epitaque** [comment]
Implemented here: https://github.com/epitaque/channel-packer-tool

I think actually resolving this issue is blocked until the tools menu is in, then I will work on integrating it.

**Comment by TokisanGames** [comment]
@epitaque The tools menu was merged in with https://github.com/TokisanGames/Terrain3D/pull/254. Feel free to submit a PR to integrate your tool now with the notes I gave you before. Thanks!

**Comment by TokisanGames** [comment]
Implemented in #259
