### ISSUE TITLE
Enable GitHub Actions

### ISSUE THREAD

**Issue by Calinou** [TokisanGames/Terrain3D#138]
I noticed this repository appears to have GitHub Actions disabled, as there's no Actions tab at the top of the repository's page. https://github.com/outobugi/Terrain3D/actions is also 404.

Is this expected? The GitHub Actions workflow currently present seems to be configured to provide builds for all platforms, which could be useful to provide Linux builds in the long run.

**Comment by TokisanGames** [comment]
It would be most useful for mac builds. I don't know anything about it. Hopefully I can copy the build settings from Godot's workflows.

**Comment by TokisanGames** [comment]
Well I ran the build and it put together a package with Windows, Linux, and Android builds flawlessly. I can tweak the configuration to do separate builds and hopefully MacOS x64.

Or is there any harm in just doing one zip file with all binaries inside? I figure a gamedev making a multiplatform release will want the libraries of all systems.

**Comment by TokisanGames** [comment]
I've built out some actions. Individual platforms for testing and a combined one for releases. Still need to test if osx works, but it builds. Actions will package all releases from now on with all platform binaries.
