### ISSUE TITLE
Add detiling option to the shader

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#145]
The current rotation used for detiling is very unattractive for strong patterns like rock, and it is questionable for weak patterns like grass/mud. One user mentioned [rotation messes up normals](https://discord.com/channels/691957978680786944/1130291534802202735/1130577162563502150).

I think we should differentiate between detiling and rotation and make these changes:

* (This Issue) Include a better detiling algorithm, such as [one of these from IQ](https://iquilezles.org/articles/texturerepetition/), or one from [hterrain](https://github.com/Zylann/godot_heightmap_plugin/blob/a481edb415d29eb01f7b0f220bde301e9052dcfb/addons/zylann.hterrain/shaders/multisplat16.gdshader#L181). Either are superior to the current implementation.

* (Separate issue) Include paintable rotation in our control map so we can manually paint rotated textures like cobblestone paths and orient them properly. 

See proposed control map https://github.com/outobugi/Terrain3D/discussions/64#discussioncomment-6448308
Related to #97
This should also address #69

**Comment by outobugi** [comment]
We probably can change the de-tiling but it will be a lot slower than our current one. Our method utilizes the index blending and the de-tiling is basically free. Most de-tiling methods use noisy patterns and ours is a grid. We would need to check if neighboring indices are same, skip them and do the de-tiling. See updated #64

**Comment by Xtarsia** [comment]
![image](https://github.com/TokisanGames/Terrain3D/assets/69606701/b41da4a3-7aaf-4e4c-a2c4-71c1e2d4313b)

https://github.com/TokisanGames/Terrain3D/assets/69606701/9574e60e-09ca-4ac4-bd9e-fd203318f62e

Along side Per Texture, UV Scale & UV Rotation;
 a UV Rotation Blend value would be very handy. (some textures need hardly any at all, making de-tiling almost free for those cases)

Currently as implemented the performance hit to enable de-tiling is between 5-15% increase in sample reads.
The limit if setting blend to absolute maxium is 100% (double) but anything past 20% is kind of redundant.

and note 1 optimisation as im typing this: can disable when blend value is at maxium)

(some minor optimisations / refactoring to fit with the rest of the base shader aside)

**Comment by JekSun97** [comment]
> We probably can change the de-tiling but it will be a lot slower than our current one. Our method utilizes the index blending and the de-tiling is basically free. Most de-tiling methods use noisy patterns and ours is a grid. We would need to check if neighboring indices are same, skip them and do the de-tiling. See updated #64

Please do not add anything that will worsen optimization

**Comment by TokisanGames** [comment]
This is already completed. See the end of this video. https://x.com/TokisanGames/status/1793957324069158955?t=xkVLzEQiI453cZVojmmBbA&s=19

**Comment by JekSun97** [comment]
> This is already completed. See the end of this video. https://x.com/TokisanGames/status/1793957324069158955?t=xkVLzEQiI453cZVojmmBbA&s=19

Wow! it is excellent! As far as I know, this doesn't even exist in Unity.
