### ISSUE TITLE
Crash while saving project with large data

### ISSUE THREAD

**Issue by paxetgloria** [TokisanGames/Terrain3D#159]
I get this error in the console
![image](https://github.com/outobugi/Terrain3D/assets/26697560/33c4c419-7852-43bf-9373-d32954db2323)

I'm using the Demo scene so all the settings are the same.
Repro:
- import terrain_8k.exr and ter_texture_8K.png with "Import Position" at -8192 0 - 8192
- import second batch at 0 0 -8192
- save the project -> crash
Note that it doesn't crash when saving after importing only one 8k tile.

Data to reproduce the crash was already shared with the devs.

**Comment by TokisanGames** [comment]
If you click the arrow on the right of the storage resource and click save, that's when it crashes. CTRL+S just calls the resource saver to save independent of our code. It's a known engine bug https://github.com/godotengine/godot/issues/62585

The crash occurs after 1,073,741,824 (~1gb) and with only 8k by 16k we're looking at 1.4gb or 2.8gb for 16k x 16k.

**Comment by TokisanGames** [comment]
I built Godot using the two PRs mentioned and it no longer crashes, but it does corrupt the file and still overruns the cowdata limits. Follow up here https://github.com/godotengine/godot/pull/74582

**Comment by CsloudX** [comment]
Maybe storage can save/load from a dir, and separate data by region? 
This has 2 advantages for large terrain:
1. can load data runtime in a const time (don't load all data one time).
2. the data file won't be too large, it was good to vcs(like only modify 1 region, not big file need commit)

**Comment by TokisanGames** [comment]
Using multiple files is possible, but I'm not excited about 256 data files. And when we expand the max region size, I don't want up to 2000 data files. Regions viewed in the distance still need to be loaded. We'll see. There are other more urgent things to build first.

**Comment by TokisanGames** [comment]
New 64-bit cowdata PR to watch. 
https://github.com/godotengine/godot/pull/86730

**Comment by TokisanGames** [comment]
Juan's PR is ready to merge in 4.3. There's a new Godot-cpp PR to work with it. This is promising and needs to be tested against a large resource file. 

https://github.com/godotengine/godot-cpp/pull/1357

**Comment by TokisanGames** [comment]
Juan's 64-bit cowdata PR has been merged. The godot-cpp PR is finished and once it's merged, we can try testing big data again. Though no idea what else is broken overall with Godot 4.3 though.

**Comment by Saul2022** [comment]
>. We can try testing big data again.

Great!!  It fixes the original godot issue so that may  make it, through do you know of any file with such size to test this ?

**Comment by TokisanGames** [comment]
It just needs saving a terrain with >100 regions. 16k is 256.

**Comment by TokisanGames** [comment]
The new PRs do not yet allow saving resource > 1gb w/o crashing. https://github.com/godotengine/godot/issues/62585#issuecomment-1901099274

**Comment by TokisanGames** [comment]
Godot won't be fixing this [until at least 4.4](https://github.com/godotengine/godot/pull/74582#pullrequestreview-2041664269), probably 6 months away minimum. And so far no pending PRs fix it so it could be much longer.

However, splitting regions into separate data files #356 will fix it. Since the opengl limit on layers is 2048, we won't have more than that number of files, which is reasonable. As long as any given region with the maps and foliage data is <1gb it won't crash, which will be very hard for users to hit. Time frame on this is 1-2 months realistically. After I finish foliage in #340, 0.9.2 will be released. Then this and dynamic collision are the top priorities.

**Comment by Saul2022** [comment]
Maybe while it known that the separate sotrage regions will fix this, atleast it seems that things are improving https://github.com/godotengine/godot/pull/94598

**Comment by TokisanGames** [comment]
@Saul2022 Thanks for the heads up, but that won't affect us. It would help if we wanted region sizes >32k. We'll probably have a limit of 2k or 4k. This issue is with writing resource files to disk.

**Comment by TokisanGames** [comment]
This has finally been fixed in #374 and #476. Rather than waiting for Godot to fix saving resource files >800mb, we split data into one file per region and can now save a 16km^2 terrain.
