### ISSUE TITLE
Link against the modern Windows 10 C++ runtime when using MSVC

### ISSUE THREAD

**Issue by Calinou** [TokisanGames/Terrain3D#189]
I noticed the binary Windows releases depend on the MSVC redistributable on being installed: https://github.com/outobugi/Terrain3D/releases

This can be an issue for projects you distribute, as fresh Windows installations don't have that redistributable package installed unless you happen to have installed another software that requires it. I suggest linking to the modern Windows C++ runtime which is bundled in Windows 10 and later instead. This way, users won't need to install a separate redistributable. The downside is that this raises the Windows version requirement to Windows 10, but I don't expect a lot of users running projects with advanced 3D terrain to be using Windows 7/8.1.

The alternative is to use MinGW for binary Windows releases, similar to official Godot builds.

**Comment by TokisanGames** [comment]
I'm setup to build with mingw, but it adds 7mb to the dll (as does the linux build). I could do that or statically link the msvc library. But I didn't know I can link against libraries already in windows. 

Is this the MS Universal CRT? It looks like it is downloadable for win7-8 if needed.

Can you give me more direction on how to link against it using scons? I did a bit of looking through these links and am not quite sure. Do I just add `env.Append(CXXFLAGS="/MD")`?

https://stackoverflow.com/questions/61375024/upgrading-to-universal-crt-how-can-i-get-rid-of-a-dependency-on-vcruntime140-dll
https://stackoverflow.com/questions/31527969/how-to-i-update-my-c-project-in-visual-studio-2015-to-use-the-new-universal-cr
https://learn.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-170&redirectedfrom=MSDN
https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170
https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/
https://www.microsoft.com/en-us/download/details.aspx?id=48234

**Comment by Calinou** [comment]
> Is this the MS Universal CRT? It looks like it is downloadable for win7-8 if needed.

I think so.

> Can you give me more direction on how to link against it using scons? I did a bit of looking through these links and am not quite sure. Do I just add env.Append(CXXFLAGS="/MD")?

Unfortunately, I don't know how you'd go about this with SCons.

**Comment by TokisanGames** [comment]
Godot uses /MT when building with MSVC, which statically links the native multithreaded CRT.

`cl /Focore\core_constants.windows.editor.x86_64.obj /c core\core_constants.cpp /TP /std:c++17 /nologo /MT ...`

But our default setup is using /MD which means statically link the native CRT w/o multi threading, yet our file is still linked to the redistributable. 🤔 

In any case, from now on, release builds will be made with CI using mingw and the requirement for msvc runtime libraries will be dropped.

https://github.com/TokisanGames/Terrain3D/actions/runs/6003166159
