### ISSUE TITLE
Lock  to a specific material when painting color in terrain.

### ISSUE THREAD

**Issue by Saul2022** [TokisanGames/Terrain3D#192]
It may seem confusing but the idea is that  when painting a color you can go to the surface list, select the material you want and it will only paint on that material., taking advantage that now you can assign names to the textures and maybe in the future could be applied to the foliage feature when it comes to paint on a specific material, though 
 there can be an option in the color brush sethings where you can unlock that and paint on whatever material you want.

--------
Admin edit:
* Limit painting of color, texture, scale, rotation, foliage to a texture layer mask that are already present on the terrain (eg. a layer chooser in the inspector like collision mask or render layers)

**Comment by TokisanGames** [comment]
It could be paintable on only one texture. However there's only one color map and it gets multiplied to albedo as a whole. So there might be some bleed where the textures blend. We'll see if it's usable.

**Comment by Xtarsia** [comment]
#360 would work for having seperate paintable color for base / overlay.

**Comment by TokisanGames** [comment]
I agree the feature is useful. Often times I've wanted to use the colormap to darken mud to make it wet in a pig sty. But I don't want to darken the adjacent grass that its blended into.

**Comment by TokisanGames** [comment]
Added filtering to color and wetness in #492. However we aren't doing a weighted blend on the colormap, so if the color is too contrasted, it will get blocky.
![Image](https://github.com/user-attachments/assets/aaa16444-2810-4219-9187-83a0f7e5a73c)
![{54629409-E6AC-42C7-ACBC-888CD6CC76A6}](https://github.com/user-attachments/assets/6b660bac-696b-4afa-b872-e40381e0b9b9)
