### ISSUE TITLE
No collisions for code generated terrain 

### ISSUE THREAD

**Issue by qawsedrftgzh** [TokisanGames/Terrain3D#193]
## steps to reproduce

- run /demo/CodeGenerated,tscn
- try to land on terrain

## expected behavior

player doesn't fall trough terrain

## actual behavior 

player falls through terrain

![grafik](https://github.com/TokisanGames/Terrain3D/assets/59800573/02110c4e-e894-4219-8cff-0833ae61014b)

If you have the same problem you could try to use terrain.storage.get_height() for generating a collision with a CollisionShape3D with an HeightMapShape3D or limit the minimal position.y to the terrain height

**Comment by qawsedrftgzh** [comment]
## Solution 1 - limiting the position of object
### for
fast
### against
when walking against walls or steep hills there is no resistance, the player is teleported up

### code
add this to _physics_process of your player
`if position.y <= get_parent().get_node("Terrain3D").storage.get_height(Vector3(position.x,0,position.z)):
		position.y = get_parent().get_node("Terrain3D").storage.get_height(Vector3(position.x,0,position.z))
		velocity.y = 0`

**Comment by TokisanGames** [comment]
The C++ code already supports collision for code generated terrain. It just needs to be regenerated after making the terrain.
