### ISSUE TITLE
Changing the scale of the terrain/regions

### ISSUE THREAD

**Issue by LoipesMas** [TokisanGames/Terrain3D#198]
I'm making a game, which operates on a smaller scale than your typical open world game, so I would like to trade size for detail. My map doesn't even fill a single region.

I think a property like "Terrain scale", which would just scale the mesh and the colliders, would solve that issue.

As a workaround, I could scale up everything else, but that's a lot (models, colliders, values in resources and scripts, etc.) and it doesn't seem like a good solution.

#77 and #131 are kinda related, but I don't need more detail in the region, I just need the region to be smaller (while keeping the resolution), so that 1 "pixel" is, for example 0.5m, instead of 1m.

I hope it makes sense and is possible, thanks!

**Comment by TokisanGames** [comment]
> #77 and #131 are kinda related, but I don't need more detail in the region, I just need the region to be smaller (while keeping the resolution), so that 1 "pixel" is, for example 0.5m, instead of 1m.

#131 - Change density from 1px=1m to 1px=0.5m or 1px=2m. With a 1024px map, 1024m=512m or 2048m
#77 - Change region map size from 1024px to 512px or 2048px

It sounds like you want #131 exactly. How is your request different?

**Comment by TokisanGames** [comment]
> With #131 without #77
> If I would set density to 2.0, what would be the result?
> 1024px region_size -> 512m in game size
> 2048px region_size -> 1024m in game size
> I thought it would be 2., that's why I said it was different. 

2 requires both #131 and #77 and is not possible without it.

> With #77 (without #131)
> 512px region_size -> 512m

Yes

> But if it would be 1., then that's the same.
> I hope this helped clear things up

Ok, thank you.
