### ISSUE TITLE
Terrain3D not illuminated by baked lightmap

### ISSUE THREAD

**Issue by cammySashimi** [TokisanGames/Terrain3D#205]
I've noticed that terrain is only lit by real-time lights, not baked lightmaps. For performance and visual reasons, I'd like to disable the real-time lighting in my game. Here's an example of how things look with my real-time OmniLight3Ds enabled:

![Screenshot_20230916_110913](https://github.com/TokisanGames/Terrain3D/assets/10779248/6ec41c06-9a2d-4aef-a5cc-f28256f14f59)

and disabled:

![Screenshot_20230916_110902](https://github.com/TokisanGames/Terrain3D/assets/10779248/73ac5dc6-d7eb-45be-a584-2291239f6d8a)

I'd love some advice on how to illuminate the terrain with a baked lightmap. Apologies if this is out of scope, or if I'm simply missing something obvious.

**Comment by TokisanGames** [comment]
It is not possible. Please read the Godot docs on how the different types of lighting works. Baked requires a uv2 channel on the mesh. We have neither a static mesh, nor a uv2 channel since it's a clipmap mesh. Dynamic lighting only, including sdfgi.

This was detailed on this page
https://github.com/TokisanGames/Terrain3D/wiki

**Comment by cammySashimi** [comment]
Oh my apologies, I totally missed that bit on the wiki. Thanks for the response!

**Comment by TokisanGames** [comment]
No problem. I'd like to bake too, but the only way is if you have a mesh terrain, eg from blender, but that may be worse performance due to lack of lods or culling.

**Comment by cammySashimi** [comment]
Is there a way I can export the heightmap data from my terrain to try making it into a mesh via a displacement modifier in Blender? My game currently only uses one terrain chunk and I'd be interested in testing the performance of a mesh in its place.
