### ISSUE TITLE
Clarify texture format

### ISSUE THREAD

**Issue by ZaPx64** [TokisanGames/Terrain3D#208]
Hey there, I'm using Substance Designer to generate channel packed dds textures as defined in the docks. However, when I try to use them on the terrain, I get `Invalid format. Expected channel packed DXT5 RGBA8`. This happens regardless of the format used - dds or png won't work either for me. Is there some hidden requirement for the textures not mentioned in the docs?

**Comment by SkellySoft** [comment]
On the "Setting Up Textures" page on the wiki (https://github.com/TokisanGames/Terrain3D/wiki/Setting-Up-Textures), there is a section that mentions how to set up the DDS textures. I personally had issues trying to set up textures until I tried using NVidias Texture Tools, converting a png to a DDS that way - so I'd personally say you should create your textures as PNGs in Substance Designer then try converting them through the NVidia tools. If that doesn't work, though, you might have to wait until TokisanGames get back to you for some more help.

**Comment by TokisanGames** [comment]
What else do you need to know? The format is explicitly defined with an exact step by step process with free tools to make the images and set them up in Godot. In fact there are three free tools mentioned that can easily make the files.

What exact format are you saving in? DDS and PNG are just containers that hold many configurations within.

**Comment by ZaPx64** [comment]
I'm exporting DXT5/BC3 as specified in the docs. I have tried dds, png each with linear and raw color space. Channels are packed as described in the docs too, hence the confusion. I'm assuming there must be some difference in the exports between Substance and Gimp. I will analyze the example files compare them with my exported files and let you know.

**Comment by TokisanGames** [comment]
If Godot complains about your file on the console, and when double clicking the file you cannot open it in the inspector as follows, then it cannot read the file. If Godot cannot read the file, neither can we.

![image](https://user-images.githubusercontent.com/180032/262065171-c9bddf30-a186-45d0-b26a-bd4265878e37.png)

You should be able to get data about your files from Godot in the inspector (if it can read them), and also open them up in photoshop (w/ intel's dds plugin) or gimp to see all 4 color channels and mipmaps, as shown in the screenshots in #190.

**Comment by ZaPx64** [comment]
Apparently the dds files have not been exported with DXT5 format even though it was configured so in the exporter in Substance. So it's a bug on their side. I was able to validate and also fix that with [AMD's compressonator](https://github.com/GPUOpen-Tools/compressonator). Thanks for your help, looking forward to explore this awesome terrain solution 🙂

**Comment by TokisanGames** [comment]
Excellent, thanks for the report. Please tag me on Twitter with any cool stuff made with Terrain3D.
