### ISSUE TITLE
Implement Procedural Generator

### ISSUE THREAD

**Issue by thephox1982** [TokisanGames/Terrain3D#210]
This plugin is wonderful but I haven't seen anything in relation to procedural generation other than from a heightmap image based on ones location. What I am needing is the ability to generate terrain based on position via a seed system, so that the same geography is present whenever the player visits the area again in the future. The user must also be able to terraform the terrain and it be saved for later loading when they revisit the area.

This would be similar to say MapMagic 2 which is a Unity asset.

If this is possible by using another plugin along with Terrain3D, I'd like to hear about that!
Otherwise it might be something to consider adding to Terrain3D as a powerful feature for open worlds.

**Comment by TokisanGames** [comment]
You can generate your own terrain in code right now. There's even a demo for it. But the demo gets a default 8-bit image from the noise library and it looks terrible. But you can make your own 16-bit or 32-bit image from the noise library and use that to make your own maps. Whatever seed settings you put into the library will generate the same noise map. 

We may include a generator in the UI to create a base for sculpting, but everything you need to do it in the editor or in game is there right now.

**Comment by TokisanGames** [comment]
Actually, contrary to the last comment, procedural generation is already tracked in #101. So with the codegenerated demo showing how to generate a noise image to create a terrain at runtime, and #101 providing more image generation options, this ticket is a duplicate. There are no plans to create terrains that are not based on a heightmap image, purely algorithmic, or runtime user modification. Zylann's voxel tools is the best system for those.
