### ISSUE TITLE
Terrain 3D Does Not Work With Godot 4.1.1

### ISSUE THREAD

**Issue by bbacle** [TokisanGames/Terrain3D#211]
The terrrain 3D does not work with Godot 4.0 or 4.1.1.
I get the error message as follows:
Unable to load addon script from path: 'res://addons/terrain_3d/editor/editor.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/terrain_3d/plugin.cfg' to prevent further errors.

**Comment by TokisanGames** [comment]
Improper installation. Terrain most definitely works with 4.1.1, using the release package for 4.1.1. Run Godot using the console as described in the troubleshooting page so you can get all of the console errors and read them. They will most likely tell you it can't read the library and give you the file path it's looking for. Compare with what is on your disk. You probably put the files in the wrong folder.

**Comment by svencan** [comment]
Make sure to download the release (https://github.com/TokisanGames/Terrain3D/releases), not the main branch of this repository.

**Comment by TokisanGames** [comment]
@svencan Ah, good call. On discord Op posted a console message sharing a filename of `Terrain3D-main` indicating the repository source code was indeed download, instead of the binary release. Exactly as occurred in #200. 

The directions right on the front page say to download the binary releases.
