### ISSUE TITLE
Scatter Script Fails To Load 

### ISSUE THREAD

**Issue by nubbyninja** [TokisanGames/Terrain3D#213]
Scatter Script Fails To Load 
Error Message: "Error: Failed to load script project_on_terrain3d.gd"

Followed instructions, copied into correct folder, uncommented lines below the instructions.

How to proceed?

**Comment by nubbyninja** [comment]
May want to add to comments in the project_on_terrain3d.gd script to **Delete the instructions after uncommenting everything else, for those coming from c# unaware of the gdscript requirements.** <3 Closed.

**Comment by TokisanGames** [comment]
I don't understand. There are no comments after @ tool, and it works fine to leave the comments at the top.

**Comment by nubbyninja** [comment]
The plugin failed to load until I deleted the commented lines at the top completely. It didn't make sense to me either. 
For context I'm using the latest Mono version.

**Comment by TokisanGames** [comment]
Ok. Works fine in our game on 4.1.1-stable.

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/50d1c158-1b57-4f69-8baa-7bb0dcd706ef)

**Comment by nubbyninja** [comment]
Weird....  I don't have an explanation but I'm happy to try and reproduce if it'll help.
