### ISSUE TITLE
[4.2] Terrain3D broken in godot 4.2dev5+

### ISSUE THREAD

**Issue by WrobotGames** [TokisanGames/Terrain3D#214]
Terrain3D does not work in godot 4.2dev5, it worked in 4.2dev4.
System information: Windows 11, tested on an intel and an amd cpu. Tested on a nvidia and an amd gpu.
While opening the scene I get these errors:
```
  core\extension\gdextension_interface.cpp:1327 - Hash mismatch for method 'Image.resize'.
  godot-cpp/gen/src/classes/image.cpp:122 - Method bind was not found. Likely the engine method changed to an incompatible version.
  core\extension\gdextension_interface.cpp:1327 - Hash mismatch for method 'Object.connect'.
  godot-cpp/gen/src/classes/object.cpp:316 - Method bind was not found. Likely the engine method changed to an incompatible version.
  core\extension\gdextension_interface.cpp:1327 - Hash mismatch for method 'RenderingServer.mesh_add_surface_from_arrays'.
  godot-cpp/gen/src/classes/rendering_server.cpp:429 - Method bind was not found. Likely the engine method changed to an incompatible version.
  servers\rendering\renderer_rd\storage_rd\mesh_storage.cpp:522 - Index (uint32_t)p_surface = 0 is out of bounds (mesh->surface_count = 0).
  servers\rendering\renderer_rd\storage_rd\mesh_storage.cpp:522 - Index (uint32_t)p_surface = 0 is out of bounds (mesh->surface_count = 0).
  servers\rendering\renderer_rd\storage_rd\mesh_storage.cpp:522 - Index (uint32_t)p_surface = 0 is out of bounds (mesh->surface_count = 0).
  servers\rendering\renderer_rd\storage_rd\mesh_storage.cpp:522 - Index (uint32_t)p_surface = 0 is out of bounds (mesh->surface_count = 0).
  servers\rendering\renderer_rd\storage_rd\mesh_storage.cpp:522 - Index (uint32_t)p_surface = 0 is out of bounds (mesh->surface_count = 0).
```
The scene does open and the ui works but the is just no terrain.
Screenshot from the demo scene:
![afbeelding](https://github.com/TokisanGames/Terrain3D/assets/66079814/fc634dff-837b-43e8-9f48-ba3aefe84403)

**Comment by TokisanGames** [comment]
4.2 won't be released until November, and godot-cpp hasn't even been synced to 4.1.2, let alone 4.2. Until then, the API is a moving target. This is not a core part of the engine. We are downstream 3 levels so cannot and will not be in sync with the engine master branch. I have no plans to support 4.2 until around release time. However, I will accept PRs as long as they do not break compatibility with the current stable version.

**Comment by WrobotGames** [comment]
I guess this was just a random bug I had with my godot version/install/whatever it may be, because it works in the current master build and it somehow works in 4.2dev5 too. 

I hope no one spend a lot of time on this...
