### ISSUE TITLE
Brushes snap to terrain grid and causes blockiness

### ISSUE THREAD

**Issue by LxrdKxnny** [TokisanGames/Terrain3D#215]
I've just started working with Terrain3D and I like it so far, but the terrain, when using a smaller brush, seems to appear blocky where edits were made, such as when adding paint, raising, and lowering the terrain, etc. I'm not sure if this is something we can disable or enable depending on our preferences. Please see the attached screenshots below to get an idea of what I am referring to, as well as the mini clip I created that shows the brush snapping to the grid.

![image](https://github.com/TokisanGames/Terrain3D/assets/94867124/c6f8c5b8-7abf-4e6e-8705-07e883f2dd57)

![image](https://github.com/TokisanGames/Terrain3D/assets/94867124/a0ad6e9b-3b93-42e0-a601-7dee044bb607)

https://github.com/TokisanGames/Terrain3D/assets/94867124/e6fbfd1f-94a8-460c-85ea-7716a3ecedaf

**Comment by TokisanGames** [comment]
You can only paint where there are vertices. They exist every 1m. Turn on wireframe view to see them. #131 aims to provide variable resolution.

**Comment by LxrdKxnny** [comment]
> You can only paint where there are vertices. They exist every 1m. Turn on wireframe view to see them. #131 aims to provide variable resolution.

Thank you! :)
