### ISSUE TITLE
Support Compatibility Renderer

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#217]
Switch to compatibility mode and the textures are black. Supposedly texture arrays are not supported. However height and the colormap are there, so some texture arrays are being read. So it's unclear what is supported exactly.

Also opengl doesn't support FMA, so a macro should be made to replace fma with `*+` via code or have two separate shaders.

Waiting for OpenGL support in Godot:
* Tracker https://github.com/godotengine/godot/issues/66458
* TextureArray support https://github.com/godotengine/godot/issues/71029 
* TextureArray PR https://github.com/godotengine/godot/pull/80363

**Comment by directedchaossoftware** [comment]
I wonder if this would help iOS, where I am seeing the heightmap mesh (including shadows) but with the "chess squares" shader issue (as if it had no textures?).  This is with the Godot Project Settings->General->Renderering->Renderer->Rendering Method options: forward_plus or mobile (gl_compatibility shows an all grey plane, no height at all or squares).

It looks like iOS is unsupported, but I managed to build for iOS (scons platform=ios), updated the `terrain.gdextension` file to point to the resulting `libterrain.ios.debug.universal.dylib` and exported without much trouble (and some hints from the [Android discussion](https://github.com/TokisanGames/Terrain3D/issues/197)).

**Comment by TokisanGames** [comment]
If you can render forward_plus or mobile, then that is not related to this issue. What you see on gl_compatibility is this thread.

Thanks for letting me know about ios builds. This is the first I've heard about anyone trying it. Please post the full lines that you put in terrain.gdextension. It will help for later when it does maybe become a supported platform. You can make a separate ios support thread if you like so we can keep the discussions focused.

The chess squares are textures generated and placed in the texture list. If the forward renderer is displaying them, then there might be another issue as to why the grass/rock textures aren't showing, such as something with export. Let's discuss further on an IOS thread.

**Comment by TokisanGames** [comment]
Apparently shadows aren't included in the compatibility renderer yet. Who knows what else isn't finished. This should wait until 4.2 is out with its compatibility shader improvements

https://github.com/godotengine/godot/pull/77496

**Comment by filipworksdev** [comment]
you can see here what is and isn't finished https://github.com/godotengine/godot/issues/66458

**Comment by TokisanGames** [comment]
Here specifically texturearrays are not supported. (even though we read them for height and color) the issue shows it doesn't work for albedo. 

https://github.com/godotengine/godot/issues/71029

**Comment by JohnathonNow** [comment]
Looks like some big progress towards support got merged last night. There's some wonkiness with the shader but I at least see textures on a web build now.

**Comment by TokisanGames** [comment]
> Looks like some big progress towards support got merged last night. There's some wonkiness with the shader but I at least see textures on a web build now. 

That's good news.

> Edit: biggest issue seems to be that usampler2Ds don't seem to work. 

The control map uses usamplers for texture placement. You should get no textures if it's not working, or a broken shader if it's an unsupported command.

> I wonder if you can work around it with floatBitsToUint?

Yes, you could change the usampler to sampler and wrap the control texelfetches with floatBitsToUint().

But if it's true that usamplers are not supported in opengl, then the better solution is for Godot to [support standard opengl formats](https://github.com/godotengine/godot-proposals/issues/7540), including usamplers (which may not have a separate ticket) and that we [stay on them](https://github.com/godotengine/godot/issues/66458#issuecomment-1772682476) until these issues are tracked and implemented.

We store the control map as a 32-bit uint directly in memory, then the shader reads a 32-bit uint out of memory. The whole path through the Image/Texture/RenderingServer/RenderingDevice Godot thinks of that portion of memory as an RF32 float, but we don't care because it doesn't change it. The contents of that memory are a 32-bit uint. If read as a float it's garbage data. See all of this ticket, especially my final comment regarding using usamplers and encoding floats.
https://github.com/godotengine/godot/issues/57841#issuecomment-1773930802

**Comment by TokisanGames** [comment]
Minor update:
* In 4.2.2, the minimum shader works with the compatibility renderer to produce a greyscale terrain with heights.
* [The PR ](https://github.com/godotengine/godot/pull/80363) to provide 3D textures support to allow us to get albedo textures out of the texture array was merged into 4.3, but not 4.2.
* A custom shader that adds your own texture uniforms and works. One could copy the autoshader code out of the main shader and have a nice looking terrain right now with only two textures, just like the demo.
* The mouse cursor doesn't work, as it is a GPU driven, so no sculpting in this mode. Perhaps the GPU mouse will work in 4.3 or with some minor adjustment to the shader. Otherwise, we'll need to have a non-gpu fallback, returning to [this version](https://github.com/TokisanGames/Terrain3D/blob/74c1435e1f73511e5f93811e1811f6e7e4febd5e/src/terrain_3d.cpp#L836-L873) of get_intersection()

**Comment by Xtarsia** [comment]
when we move to 4.3, the texture array issue is now fixed, thanks to this pr
https://github.com/godotengine/godot/issues/91365

a compatability insert that has these defines covers initial shader errors
```glsl
#define fma(a, b, c) (a) * (b) + (c)
#define dFdxCoarse(a) dFdx(a)
#define dFdyCoarse(a) dFdy(a)
#define textureQueryLod(a, b) vec4(0.0)
```
The GPU mouse needs its shader modifying, and its own defines so it can work correctly in compatability.

the only thing left is the decal, which can be drawn directly on the terrain (we could move to this for all render modes.)

**Comment by TokisanGames** [comment]
PR #500 provides support for Compatibility and maybe webgl if you guys want to test and review it. 4.3 recommended. 4.2 works if you import your textures as Lossless.

cc: @Saul2022

**Comment by Xtarsia** [comment]
@Saul2022

there is, linked at the bottom of the PR. (tho its of the original PR for now)

**Comment by TokisanGames** [comment]
Compatibility mode has been implemented. Try it out in nightly builds. Read about caveats here
https://terrain3d.readthedocs.io/en/latest/docs/platforms.html#compatibility
