### ISSUE TITLE
Add iOS Support

### ISSUE THREAD

**Issue by directedchaossoftware** [TokisanGames/Terrain3D#218]
### Overview

I am new to Godot and Terrain3D, but have been experimenting.  I managed to mostly get iOS working without much trouble, maybe solving 2 of 3 issues/steps, after some setup from [building from source instructions](https://github.com/TokisanGames/Terrain3D/wiki/Building-From-Source).

### Steps

1. [Local Fix] Building iOS libraries
```
scons platform=ios target=template_debug
[...]
scons platform=ios target=template_release
```
Note: there are some deprecation warnings.

2. [Local Fix] Updating terrain.gdextension:

```
[...]
ios.debug = "res://addons/terrain_3d/bin/libterrain.ios.debug.universal.dylib"
ios.release = "res://addons/terrain_3d/bin/libterrain.ios.release.universal.dylib"
```

3. [WIP] Fixing textures

With the first two changes and the normal iOS export templates from the Godot editor, I am seeing a "chess squares" shader issue (as if it had no textures?) actually on device.  I have a separate C++ GDExtension moving the character and camera slightly to confirm code is running.  Also note shadows and occlusion look to be working.

![image1](https://github.com/TokisanGames/Terrain3D/assets/4149680/2fbfa8f3-42a8-4e72-a282-80bbe03747aa)
![image0 (1)](https://github.com/TokisanGames/Terrain3D/assets/4149680/65862317-35ca-4dfc-b96e-047f29359818)

### Other Thoughts
**Rendering**: This is with Godot Project Settings->General->Renderering->Renderer->Rendering Method options: forward_plus or mobile.  gl_compatibility shows an all grey plane, no height at all or squares, which is a different issue.

**Exporting**: I am not an artist, but one [suggestion](https://github.com/TokisanGames/Terrain3D/issues/217#issuecomment-1735106187) from that other issue was to investigate the texture exports themselves.   I followed [Texturing the Terrain](https://github.com/TokisanGames/Terrain3D/wiki/Setting-Up-Textures#texturing-the-terrain), using the highly recommended DDS settings using GIMP-2.10.  It renders fine in editor, export to mac and windows.

![Screenshot 2023-09-26 at 9 27 17 PM](https://github.com/TokisanGames/Terrain3D/assets/4149680/e515d0fe-71d5-4ba4-813c-32b4cda25664)

**Architectures**: I did this on an M1 Mac and updated to the latest XCode.  But I am not sure that matters as it builds universal.  arm64 seems to build fine:
```
scons platform=ios target=template_debug arch=arm64
[...]
scons platform=ios target=template_release arch=arm64
```

Though the resulting libraries are exactly the same size as the universal libraries.  I haven't tried with the App Store either. The mac libraries look to not use architecture, though now I wonder if that would help arm macs.

**Comment by directedchaossoftware** [comment]
I tried removing all textures but one, painting that and white color everywhere, same result.  I also tried
[PNG](https://github.com/TokisanGames/Terrain3D/wiki/Setting-Up-Textures#exporting-as-png), but I can't get Terrain3D to accept it.

When I try to set it as an Albedo Texture I get this log (error and message):
```
  ./core/variant/variant_utility.cpp:905 - Terrain3DTexture::_is_texture_valid: Invalid format. Expected channel packed DXT5 RGBA8. See documentation for format.
Set albedo_texture
```

Similarly for Normal Texture:
```
  ./core/variant/variant_utility.cpp:905 - Terrain3DTexture::_is_texture_valid: Invalid format. Expected channel packed DXT5 RGBA8. See documentation for format.
Set normal_texture
```

I see the log line [here](https://github.com/TokisanGames/Terrain3D/blob/ca11fe337f0a0b1822a73ef12a0024c66c0037a1/src/terrain_3d_texture.cpp#L23), which sure enough requires FORMAT_DXT5, but shouldn't it also support FORMAT_RGBA8?  I see these values in the path `godot-cpp/gen/include/godot_cpp/classes`, but I can't actually find that on github now (only a couple [classes](https://github.com/godotengine/godot-cpp/tree/master/include/godot_cpp/classes)).  But the comment also says "RGBA8" in it.

I have tried exporting from GIMP with and without the [Channel Pack](https://github.com/TokisanGames/Terrain3D/wiki/Setting-Up-Textures#how-to-channel-pack-images-with-gimp) approach, and all the same checkboxes marked in the [PNG](https://github.com/TokisanGames/Terrain3D/wiki/Setting-Up-Textures#exporting-as-png) instructions.  I selected the same Godot import options as in the instructions, but there are many other settings I may have wrong:
![Screenshot 2023-09-28 at 12 49 42 AM](https://github.com/TokisanGames/Terrain3D/assets/4149680/bb363e7e-b7f6-4998-a9d8-ce7a08b7bbc5)

So, I tweaked the check to allow FORMAT_RGBA8 and error to output the format:
```
	if (format != Image::FORMAT_DXT5 && format != Image::FORMAT_RGBA8) {
		LOG(ERROR, "Invalid format. Expected channel packed DXT5 RGBA8 (or straight RGBA8). See documentation for format.  Actual value=", format);
``` 

This finally revealed it was FORMAT_DXT1.
```
./core/variant/variant_utility.cpp:905 - Terrain3DTexture::_is_texture_valid: Invalid format. Expected channel packed DXT5 RGBA8 (or straight RGBA8). See documentation for format.  Actual value=17
```
```
FORMAT_DXT1 = 17
```

I'm not sure if I'm exporting or importing the PNG incorrectly, or if that would help the iOS issue (and I'm probably misunderstanding a couple other things too).

**Comment by directedchaossoftware** [comment]
Oh I also tried the demo [ground_037](https://github.com/TokisanGames/Terrain3D/blob/ca11fe337f0a0b1822a73ef12a0024c66c0037a1/project/demo/textures/ground037_alb_ht.dds) texture.  The editor sets it fine, but on export to iOS the same chess board no texture pattern appears.

**Comment by TokisanGames** [comment]
> Would Project Settings->Rendering->Textures->VRAM Compression->Import ETC2 ASTC: On be an issue? 

Is it an issue on desktop?

I don't know. So far we've only been using DXT5, which is S3TC. The demo textures and generated checkered textures are in this format, #19. 

It looks like godot's etc format would be FORMAT_ETC2_RGBA8 = 31

I don't know how to make that format. If you have a png with vram compression, while etc is enabled, that might make that format. 

The checkerbox is automatically generated, so it's probably using that format. But ground textures are not.  

You'll need to modify our check to accent format 31. You should also print out the format to see if the checkers are indeed 31 instead of 19.

**Comment by directedchaossoftware** [comment]
## Solved? ##
I re-added the change to output the texture format and continue regardless, showing the on-device format is 5 (FORMAT_RGBA8) and it runs fine (no texture issue).  There may have been some extra loading time (just a feeling, I have not done any profiling - I also saw a lot of warnings).  I'm a bit out of my depth with these texture options, but I'm happy to use this approach.  That is:
1) Use recommended `DDS` texture formats from docs
2) `Import ETC2 ASTC` as required for iOS (Mac still seems to work fine, I'll try Windows again later)
3) The 3 steps mentioned in this thread (see change below)

### PR ###
I went ahead and forked so I could send a [PR](https://github.com/TokisanGames/Terrain3D/pull/219) with these little changes.  After something like that (I'm happy to talk more about the better fix or let anyone else, I can just work off this for now) you still need Step 1 (Building iOS libraries -- I am not sure how to contribute those): `scons platform=ios`


## Screenshot ##
![image0 (2)](https://github.com/TokisanGames/Terrain3D/assets/4149680/7e9520ad-42f9-40a8-9e56-379f33d6481f)

## Log ##
```
[...]
Terrain3D[...] USER ERROR: Terrain3DTexture::_is_texture_valid: Invalid format. Expected channel packed DXT5 RGBA8 (or straight RGBA8). See documentation for format.  Continuing anyway.  Actual value=5
```

## Change, Solving Step 3 ##
(PR is cleaner and more limited)
Terrain3D/src/terrain_3d_texture.cpp:
```
	if (format != Image::FORMAT_DXT5) {
		LOG(ERROR, "Invalid format. Expected channel packed DXT5 RGBA8 (or straight RGBA8). See documentation for format.  Continuing anyway.  Actual value=", format);
		//return false;
```
