### ISSUE TITLE
Can endless, procedural terrain be done?

### ISSUE THREAD

**Issue by unicornlox** [TokisanGames/Terrain3D#222]
Can endless, procedural terrain be done?

**Comment by TokisanGames** [comment]
Endless terrain, generated in the shader, without collision is already being done. The noise algorithm isn't great, but you can change it to your own. An improvement is [in development](https://twitter.com/TokisanGames/status/1706382874323325392)

If you want collision, you need to generate heightmaps that currently must fit within a 16k x 16k space. This is hard coded for now, and collision is not setup for frequent, dynamic generation at the moment.
