### ISSUE TITLE
[4.2.beta1] Editor: tool parameters in wrong spot overlapping native editor tools. 

### ISSUE THREAD

**Issue by decryptedchaos** [TokisanGames/Terrain3D#231]
I'm sure not much can be done about this until RC1  4.2 is still very much a moving target,  but i thought you might want to know. 

this may be simply a Godot redesign they may have changed how the toolbar is rendered idk C++ isn't my bag I couldn't even find where that bar gets created so I just figured I'd point it out for the future. 

![image](https://github.com/TokisanGames/Terrain3D/assets/1302391/540b455b-ae71-41f4-b153-261fdb42e4b6)

**Comment by TokisanGames** [comment]
It's created in GDScript.

https://github.com/TokisanGames/Terrain3D/blob/main/project/addons/terrain_3d/editor/components/tool_settings.gd

This function is likely broken:

https://github.com/TokisanGames/Terrain3D/blob/01bd4dc112257faa09a992f9874bc0dfc4c112f6/project/addons/terrain_3d/editor/editor.gd#L217

https://github.com/TokisanGames/Terrain3D/blob/01bd4dc112257faa09a992f9874bc0dfc4c112f6/project/addons/terrain_3d/editor/components/ui.gd#L47

**Comment by mikest** [comment]
On Godot v4.2.beta1 - Windows 10.0.22621 - Vulkan (Forward+) I'm not seeing the controls come up at all. Might be related.

<img width="491" alt="image" src="https://github.com/TokisanGames/Terrain3D/assets/742517/765e1cd6-b004-4194-b4a8-24a834601519">

**Comment by shmafoo** [comment]
Idk about other Godot Versions since I'm only on 4.2 Beta but there's just one .get_parent() too many in add_control_to_bottom. Removing one solves that.

**Comment by TokisanGames** [comment]
Current `main` now works fine in 4.2beta3.

**Comment by mikest** [comment]
Fix confirmed against 4.2beta4.
