### ISSUE TITLE
Collision is not being generated

### ISSUE THREAD

**Issue by mmsdocs** [TokisanGames/Terrain3D#235]
![Captura de tela 2023-10-27 130709](https://github.com/TokisanGames/Terrain3D/assets/19829824/afa612a8-2ee9-48c1-a607-07b9a8a24fa7)
![Captura de tela 2023-10-27 131216](https://github.com/TokisanGames/Terrain3D/assets/19829824/80e4bdca-db8e-43ab-9f0c-4501d6803891)
![Captura de tela 2023-10-27 131156](https://github.com/TokisanGames/Terrain3D/assets/19829824/54a8fc7a-6f0f-4569-9dd0-4f734ca95f98)

When I run the scene, all physical objects pass through terrain, and I can't see the terrain collision shape. I had restarted the application and the problem continues. What am I doing wrong?

Specs:
- Godot: 4.1.1.stable
- Terrain3D: v0.8.3-alpha_gd4.1.1

**Comment by TokisanGames** [comment]
Does collision work in the demo?

It is only enabled for areas with regions. The picture looks like you're using world noise and haven't made any sculpted regions. 

Collision is automatically turned on. The setting is under collision and isn't in your screenshot.

**Comment by mmsdocs** [comment]
> Does collision work in the demo?
> 
> It is only enabled for areas with regions. The picture looks like you're using world noise and haven't made any sculpted regions.
> 
> Collision is automatically turned on. The setting is under collision and isn't in your screenshot.

I had not created regions for my map, I just enabled World Noise. Following your tip, now I have collisions, thank you @TokisanGames

**Comment by TokisanGames** [comment]
Ok. I plan to have a noise based terrain generator that will add noise to regions and thus have collision. World noise right now is just a visual gimmick so you can have interesting backgrounds outside of your regions. There is a new version in development that has much more attractive noise https://github.com/TokisanGames/Terrain3D/pull/216, but it is expensive.
