### ISSUE TITLE
Grid Tile id for A* nodes

### ISSUE THREAD

**Issue by Osimedias** [TokisanGames/Terrain3D#236]
Is there a way to use the terrain grid  or someting like that for astar nodes?

I have an implementation that uses the vertices of a plane to generate the nodes of the a* using MeshDataTool, but I see that the vertices of the terrain cannot be accessed from gdscript.

**Comment by TokisanGames** [comment]
Look in the wiki under system design. This is a clipmap terrain. There are no grid tiles. The vertices are not static. They move around constantly, so there is no value in accessing them, except within the shader.

There is a PR available for a makeshift navigation baker until we integrate a solution.
