### ISSUE TITLE
Brushes rotate when you click

### ISSUE THREAD

**Issue by tcoxon** [TokisanGames/Terrain3D#241]
### Terrain3D version

v0.8.3-alpha_gd4.1.1 (also main)

### Godot version

4.1.1.stable.official

### System information

Godot v4.1.1.stable - Arch Linux #1 SMP PREEMPT_DYNAMIC Tue, 10 Oct 2023 21:10:21 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (nvidia; 535.113.01) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

This issue is very visible when you use a square brush:

https://github.com/TokisanGames/Terrain3D/assets/165720/ac695af8-2f4c-4b6a-8d7b-512ddba5b1f8

It seems like when you click the brush rotates randomly(?) very briefly. The end result often isn't square, and doesn't line up with the decal.

**Comment by tcoxon** [comment]
Oops this seems to be controlled by the Jitter 'advanced' setting. Working as intended?

**Comment by TokisanGames** [comment]
Yes, turn off jitter if you don't want it to rotate. Feature not a bug.
