### ISSUE TITLE
Is it possible to have different base textures?

### ISSUE THREAD

**Issue by less0** [TokisanGames/Terrain3D#243]
### Terrain3D version

v0.8.3-alpha

### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Windows 11 Pro, NVIDIA GeForce MX150, Vulkan Forward+

### Is the issue reproducable in the demo?

Yes

### Issue description

I ran into the following issue, while trying to paint snow covered mountain peaks: The snow texture does not blend neatly over the peaks, but is cut, which makes the texturing of the terrain less visually appealing than I hoped for. After trying around a bit, it seems to me as if the texture with index 0 is always the base texture for the whole terrain and everything else is painted as the blend texture. As my grass texture was the base texture, the rocks I used for the mountains is drawn as the blend texture and thus the snow is not blended with the rocky texture, but it is replaced instead.

I could make the rock texture the base texture without problems, but in this case I wouldn't be able to blend different ground textures (e.g. grass and soil). Is there a way to make the rock texture the base texture for the mountains only (and use blending to soften the edges) so that I can both blend multiple ground textures and blend the snow over the mountains? Or is this not possible by design?

**Comment by TokisanGames** [comment]
> Is it possible to have different base textures?

Any of the 32 textures can be the base texture or the overlay texture.


> I ran into the following issue, while trying to paint snow covered mountain peaks: The snow texture does not blend neatly over the peaks, but is cut, which makes the texturing of the terrain less visually appealing than I hoped for. 

Do you have a picture?

> After trying around a bit, it seems to me as if the texture with index 0 is always the base texture for the whole terrain and everything else is painted as the blend texture. 

Within your defined regions, the base texture is whatever texture you paint for the base, or the overlay. Outside of regions the texture is always 0. You can change that in a custom shader. #48 is working on redefining what happens outside of regions.

Most likely the issues you have are one or both of:
* Your textures don't have good height maps, so they don't height blend well together.
* Your technique needs improvement. Our system is immature and not intuitive. It will take time to refine. However, I get adequate results by painting the base textures, then spraying the edges to blend.

> Is there a way to make the rock texture the base texture for the mountains only (and use blending to soften the edges) 
> so that I can both blend multiple ground textures and blend the snow over the mountains?

That is how the system works. By mountains we are referring only to the mountains you sculpt. Not the world noise hills that can be enabled outside of regions.

Here in a few minutes I sculpted a hill, base painted rock, and base painted a rocky path. Then I sprayed snow over both. I also sprayed rock along the edges of the path where it needed blending.

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/b324f0d4-6e80-4bb4-9acf-b4efe5eb824f)

**Comment by less0** [comment]
@TokisanGames Thank you very much for your detailed answer. Great to hear that it does indeed work.

> Your technique needs improvement. Our system is immature and not intuitive. It will take time to refine. However, I get adequate results by painting the base textures, then spraying the edges to blend.

Since different combinations worked for me with blending, depending on the indices of the textures, I guess that this is the issue. So I will have to try around a bit to learn how the system works the best. Again, thank you very much. Bringing such a project from in-house to a community requires a lot of effort and dedication and I'm very grateful that you were willing to take that path.
