### ISSUE TITLE
Let Terrain3DEditor can run in runtime when export

### ISSUE THREAD

**Issue by CsloudX** [TokisanGames/Terrain3D#257]
### Description

I want change my terrain runtime in game, and try coding like this:
![image](https://github.com/TokisanGames/Terrain3D/assets/35988767/bf3027ef-62a9-42aa-8281-de8b4267b11e)
It like Terrain3DEditor can only run in editor. I wish can unfreeze this limit.

### Are you willing to help create this feature?

No

**Comment by CsloudX** [comment]
It like I can use TerrainStorage.set_map_region. so I close this.
![image](https://github.com/TokisanGames/Terrain3D/assets/35988767/961de201-a240-4253-937c-ad5b95d2cdc1)

ADDTION: It was slow, wish can speed up.

**Comment by TokisanGames** [comment]
The editor plugin is written in GDScript and uses the gdextension to modify the terrain. Though our plugin isn't designed for realtime modification, you can edit it as the editor does. Look closer at editor.gd and all the other GDScript. It instantiates Terrain3DEditor and edits the terrain from GDScript just fine.

> ADDTION: It was slow, wish can speed up.

The editor edits at an adequate speed. You can edit a lot faster by redesigning your code.

**Comment by CsloudX** [comment]
> The editor edits at an adequate speed. You can edit a lot faster by redesigning your code.

Yes, I'm test again, it speed was not slow
![image](https://github.com/TokisanGames/Terrain3D/assets/35988767/63d7986c-7803-416b-90ea-7f09f7693c26)
I feel slow it because the `ResourceSaver.save` take too much time. when comment this line, it can modify terrain runtime very well.
![GIF](https://github.com/TokisanGames/Terrain3D/assets/35988767/5a09e3b4-5eb1-4e6c-b7d1-c8e21e53897c)
So love this plugin.
ADDTION: I'm not found which api for update region's collision?
