### ISSUE TITLE
implement TerrainStorage.get_region_pixel_pos(global_position:Vector2)->Vector2i

### ISSUE THREAD

**Issue by CsloudX** [TokisanGames/Terrain3D#258]
### Description

I want modify terrain when game runtime. but there was no a function for get the Image's pixel position with global_position.
Now I'm solved this problem by look at the Terrain3DEditor C++ code, but I wish can has api for GDScript.
![image](https://github.com/TokisanGames/Terrain3D/assets/35988767/db968ba5-acc7-4714-8fd7-8c47ce842f22)

### Are you willing to help create this feature?

No

**Comment by TokisanGames** [comment]
There is an API. All of the get pixel variants take a global position. Why can't you use this? 

https://github.com/TokisanGames/Terrain3D/blob/c5a72b0b7aa843e925c8f39760fb74b314c5bd4d/src/terrain_3d_storage.cpp#L1091-L1095

You just want a function that does the math of get_pixel without returning the pixel? But you can already write your own function for that as you have. Vec3 to vec2 image position is not useful without the region Id as well. Most people should use get_pixel. The reason you'd use the maps directly is if you want to use image.blit or fill. And in those cases you aren't recalculating the image position every pixel. 


> Now I'm solved this problem by look at the Terrain3DEditor C++ code

That's great, and exactly what you should be doing in both Terrain3D and Godot source when doing advanced gamedev projects.

**Comment by CsloudX** [comment]
> There is an API. All of the get pixel variants take a global position. Why can't you use this?

I'm not only want get_pixel, but also want set_pixel, so I need the true pixel of image.

**Comment by TokisanGames** [comment]
I can add set_pixel easily and see it as useful.

**Comment by TokisanGames** [comment]
Per pixel setters have been added in 6ec4f7b.

After writing to the maps, you'll need to use force_update_maps to see changes. That won't update collision. You can disable and reenable collision, but that is slow. Dynamic collision is being worked on in #161.

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/b4e6e8f3-aa53-45cb-bf70-2922ae867c74)
