### ISSUE TITLE
Add a way to raise height at the bottom of a cliff without also raising it at the top

### ISSUE THREAD

**Issue by tcoxon** [TokisanGames/Terrain3D#275]
### Description

Currently, if you have a steep cliff in your terrain and use the raise tool to increase height at the bottom of it, the terrain at the top is also raised. This creates a sharp 'lip' at the top:

[Screencast from 2023-12-13 17-29-57.webm](https://github.com/TokisanGames/Terrain3D/assets/165720/8d0e0c4d-726c-45cb-a2b5-5be3c6b28ddc)

![image](https://github.com/TokisanGames/Terrain3D/assets/165720/339d0314-56bf-48d6-8cfa-1b30d555e0c6)

Obviously these examples are very exaggerated, but the 'lip' is noticeable in smoother terrain. The opposite also happens when the lower terrain tool is used at the top of a cliff.

Lips can be fixed by using the flatten tool, but it's a bit annoying to have to do another pass over them when making small adjustments at the bottom of a cliff.

It's not really incorrect behavior, so I've reported this as a feature request. I think my intuitive expectation would be for the raise/lower tool brushes to have a vertical extent, in addition to the extents along the X and Z axes. Not sure exactly how that would be determined though.

### Are you willing to help create this feature?

Yes

**Comment by TokisanGames** [comment]
There isn't a way currently. Those steep vertical inclines are not recommended to have in your game. 
* The vertical wall stretches the vertices which stretches the texture and the collision mesh. 
* The player may be able to pop through the cliff wall when it's like that. 
* The meshes often flicked when you have perfectly vertical 90 degree meshes. Not sure why, it probably has to do with the normal calculation. 

The way I would handle this is to smooth the cliff which will condense the vertices and make the cliff wall more of an 80-85 degree angle. I'd also include bumps and height variation so it's not completely smooth. Then I'd flatten the top again if I wanted more of a sharp edge. 

3D projection can fix the texture stretching. #65 

I'm all for improving the tools as they're all clunky. If you want to add this, fine. But the other problems remain.

**Comment by tcoxon** [comment]
This is a better demonstration that doesn't rely on steep cliffs:

https://github.com/TokisanGames/Terrain3D/assets/165720/f0f3b5b4-f0d0-41e9-8518-cb78b545e898

In the middle, where the two brush strokes intersect is higher than either side. Maybe this is sometimes what you want, but I often find I need a way to clip the operation to only the vertices lower than the point clicked.

I'd like to add a tool setting to the lower/raise terrain tools. Something like "Raise only lower terrain" / "Lower only higher terrain".

**Comment by TokisanGames** [comment]
Implemented in #409
