### ISSUE TITLE
Test performance

### ISSUE THREAD

**Issue by CsloudX** [TokisanGames/Terrain3D#281]
### Description

![image](https://github.com/TokisanGames/Terrain3D/assets/35988767/bfd9718a-77a5-4748-b295-b30d804bc4cb)
I‘m create a big terrain, in editor, where was no any performace(maybe because in editor, where was no collision).
but when in game, it was very slow fps(5 fps). so I wish where can a test performance scene or document.

**Comment by TokisanGames** [comment]
I don't understand what you want, or what you did. We can't help without exact information on what you setup, how big, which options you enabled. 

Why can't you make your own test scene?

**Comment by CsloudX** [comment]
Look the image, every region was 1024x1024, and the terrain was about 70 region. in my pc(3900x, gtx1060) run low fps(5 fps).

**Comment by CsloudX** [comment]
I'm first spend much time for create the terrain ^V^. and now I found there was a performance, so I subimt this comment. and I think maybe a ferformance when use full regions(16x16 region). right? 
ADD: I love big terrain, and I wish I can use full regions in the futhure,(now I can't use full region because I can't save the scene, it will crash)

**Comment by TokisanGames** [comment]
I see the image. What I see is you have world background noise enabled at a high octave, which is very expensive. Turn it off or lower the octaves if you want more performance. Documentation is tracked in #44. 

You have collision enabled everywhere which is not optimal and consumes a ton of memory, probably 12gb for 16k collision. See #161, #278.

These are known issues. So I don't know what you want by "where can a test performance scene or document." You already are testing.

**Comment by CsloudX** [comment]
I'm first spend much time for create the terrain ^V^. and now I found there was a performance, so I subimt this comment. and I think maybe a ferformance when use full regions(16x16 region). right? 
ADD: I love big terrain, and I wish I can use full regions in the futhure,(now I can't use full region because I can't save the scene, it will crash)

**Comment by CsloudX** [comment]
No, I'm not test the performace, I only known in my pc, about 70 region can't work well, but how much it work well i don't know, maybe 30 or only 8. so I wish can a test scene or an reference information in document.

**Comment by TokisanGames** [comment]
As a game developer, you're responsible for testing the options you choose. If you enable the rendering options for MSAA and increase it 2x to 16x the latter looks better but it's slower. The former is faster but looks worse. You must find the balance for the hardware you're targeting. Same here.

The world background noise is very expensive. If you're going to keep it enabled, you have to test it to determine how much you want to use. 

Saving large scenes and dynamic collision are already known issues and being worked on. So highlighting them here is a duplicate issue. 

As for "a test scene or an reference information in document"
* What exactly would this test scene do that the demo doesn't, or that you cannot already create easily yourself?
* What specific reference information would be documented?

**Comment by CsloudX** [comment]
And I disabled the shader(Set World Background to None), the fps was 5 also. so maybe the performance was effect the collsion I think.

**Comment by CsloudX** [comment]
OK, may I was want found helps for big terrain performance. so should I close this?

**Comment by TokisanGames** [comment]
Yes, duplicate issues. Follow the issues mentioned. Dynamic collision will work within a week or two and will save dramatically on memory and performance.
