### ISSUE TITLE
Make get_texture_id report autoshader material

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#283]
### Description

It currently vec3(base/overlay/blend) but ignores the autoshader. If the autoshader is enabled, it should report that texture_id instead.

**Comment by Xtarsia** [comment]
Pending architechture changes, this should just be a case of duplicating the autoshader calculations to get correct blend value and reading the material settings for the auto texture ids / slope / falloff

**Comment by TokisanGames** [comment]
https://github.com/TokisanGames/Terrain3D/pull/371 has been merged. Now the Material can directly access Storage.
