### ISSUE TITLE
Option to scale the whole terrain in the horizontal plane

### ISSUE THREAD

**Issue by rossunger** [TokisanGames/Terrain3D#285]
### Description

I would like to be able to scale the terrain in the horizontal plane. 

I have a 2k x 2k heightmap, and I want this to take up e.g. 8km x 8km in godot units. I don't need a very high resolution terrain. My current workaround is to scale up my heightmap, but this is a waste of resources. 

Is there already an easy way to do this that I missed?

My proposal is to add an xz scale parameter to the Terrain3D class that then trickles down to all the shaders and navigation and collision.

**Comment by TokisanGames** [comment]
Duplicate #131
