### ISSUE TITLE
Proton Scatter script on working

### ISSUE THREAD

**Issue by anandbarai09** [TokisanGames/Terrain3D#287]
### Terrain3D version

v0.9.0

### System information

Godot v4.2.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - integrated AMD Radeon(TM) Vega 3 Graphics () - AMD Ryzen 3 3250U with Radeon Graphics (4 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

The proton scatter script is not working. I just Installed Proton Scatter v4. I am not able to select a terrian3d node.

![image](https://github.com/TokisanGames/Terrain3D/assets/101876993/5f09f4e8-33fd-4851-be4d-c7b047600c52)

**Comment by TokisanGames** [comment]
What exact commit of proton scatter?

Post all of those error messages. Can't help without them. Post everything in your console.

**Comment by BranDenn** [comment]
Had this same issue and was able to find a fix. 

It is an issue with proton scatter not being able to get the child nodes of the scene due to an error.

I was able to fix it by simply commenting out a line in the file "parameter_node_selector.gd" located here:
"res://addons/proton_scatter/src/stack/inspector_plugin/ui/modifier/components/parameter_node_selector.gd:67"

The line to be commented out was line 67 for me. `node_item.set_icon(0, theme.get_icon(node.get_class(), "EditorIcons"))`

![ProtonError](https://github.com/TokisanGames/Terrain3D/assets/76827979/74864f3d-a5c6-4943-8086-22797a553bfe)

**Comment by anandbarai09** [comment]
The latest proton scatter release, commit:   ca62441

There not much error log.
The error is : 
res://addons/proton_scatter/src/stack/inspector_plugin/ui/modifier/components/parameter_node_selector.gd:67 - Attempt to call function 'get_icon' in base 'null instance' on a null instance.
I think this is proton scatter internal error. Not related to project_on_terrrian3D modifier.

**Comment by anandbarai09** [comment]
Thanks, this works!

**Comment by anandbarai09** [comment]
Thanks, this works!

**Comment by anandbarai09** [comment]
> Had this same issue and was able to find a fix.
> 
> It is an issue with proton scatter not being able to get the child nodes of the scene due to an error.
> 
> I was able to fix it by simply commenting out a line in the file "parameter_node_selector.gd" located here: "res://addons/proton_scatter/src/stack/inspector_plugin/ui/modifier/components/parameter_node_selector.gd:67"
> 
> The line to be commented out was line 67 for me. `node_item.set_icon(0, theme.get_icon(node.get_class(), "EditorIcons"))`
> 
> ![ProtonError](https://private-user-images.githubusercontent.com/76827979/293503180-74864f3d-a5c6-4943-8086-22797a553bfe.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMzUxMTYsIm5iZiI6MTcwNDAzNDgxNiwicGF0aCI6Ii83NjgyNzk3OS8yOTM1MDMxODAtNzQ4NjRmM2QtYTVjNi00OTQzLTgwODYtMjI3OTdhNTUzYmZlLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE1MDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NmI2NmUxMTcwMGZjYWRlN2I5ZGI4NmMyZjMwZjFmYTc1NDU4MGU4ZjI3MThhZTBlMzMxMjA1N2Y5MGY1MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rWi1dTQ4Td028Edna9OGuwjfw6cty3zPirpybRvRgi8)

 This worked for me

**Comment by TokisanGames** [comment]
Indeed this is a scatter bug, which we can't fix or support. Thanks for providing a solution @BranDenn. You guys could report it on @HungryProton 's repo. Specifically that recent changes breaks the ability for modifier scripts to create an exported node path variable. In that function, the `parent` parameter is null.

**Comment by nanodeath** [comment]
Hello 👋 this just bit me today too, so I went ahead and filed the bug report in the other repository.
