### ISSUE TITLE
Bar icons do not take into account the scale of the editor

### ISSUE THREAD

**Issue by lulasz** [TokisanGames/Terrain3D#288]
### Description

First of all thank you for this addon. This is a small issue and does not impact the functionality of the addon, but this small thing is missing.

![image](https://github.com/TokisanGames/Terrain3D/assets/4968455/8f1d13de-8cfa-460f-b2e4-3101e29bc9c7)
Icons are always drawn at 100%, despite the different scale of the editor. (for example 200% like on the screen-shot)

**Comment by TokisanGames** [comment]
Fixed in ca7b6134becbf358dbca412861e924eda3f0bd29
