### ISSUE TITLE
Texture issues in Godot 4.3.dev2-mono

### ISSUE THREAD

**Issue by Joxno** [TokisanGames/Terrain3D#306]
### Terrain3D version

v0.9.0 & a85d40c

### System information

Godot v4.3.dev2.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

I recently upgraded a pathfinder project from Godot 4.2 to 4.3.dev2.mono and encountered a strange issue with the textures on the terrain not being applied correctly. When using the debug views to try and debug the issue the checkered debug view works just fine but the height texture debug view looks a bit strange as well.

All other tools and functionality works just fine, even colour painting.

All screenshots are from the terrain3d demo project for the purpose of reproduction of the issue.

Texture Height debug view
![image](https://github.com/TokisanGames/Terrain3D/assets/9378113/772a3eae-da9e-4938-a5b8-75671ebe64b3)

Here's a screenshot from the demo project using the default checkered texture rather than the debug view.
![image](https://github.com/TokisanGames/Terrain3D/assets/9378113/4433d3b3-1056-4b12-bec7-51568a674057)

And here is a close up screenshot when using the default demo rock and grass textures
![image](https://github.com/TokisanGames/Terrain3D/assets/9378113/d18b9ee6-c6c7-4241-b6fb-fe6bc1542c72)

**Comment by TokisanGames** [comment]
pathfinder?

They broke a few things in 4.3 shaders. I've noticed in the far distance there is some odd artifact like roughness is 0 or negative. 

If you're feeling adventurous it would help get this fixed a lot faster if you bisected the engine from 4.2.1 to master/HEAD to determine which commit broke the shaders so a ticket can be filed upstream, or appropriate changes made here.

**Comment by Joxno** [comment]
Sorry, I just meant an internal project for testing out tech stacks and workflows.
I've compiled the engine at various points between 4.2.1 and 4.3.dev2 and stumbled upon that they made some refactoring to the rendering backend https://github.com/godotengine/godot/pull/83452 as well as a possibly related issue https://github.com/godotengine/godot/issues/86628

I've now compiled the current head as of writing: 5034478 and the issue reported in this ticket seems to have been resolved.
