### ISSUE TITLE
There is no way to use this proiect as a submodule

### ISSUE THREAD

**Issue by CrayolaEater** [TokisanGames/Terrain3D#315]
### Description

I’m trying to use this proiect as a module to reduce the repo size. But at the moment this is not possible since this proiect comes already with the godot-cpp submodule. I already have this submodule inside my project, I just need the source code of the terrain and build it with my other gdextension code.

**Comment by TokisanGames** [comment]
All OSes support some form of linking and binding files and directories. 

You don't need to make us a submodule. We can live in a separate dir and your project has symlinks or hard links to the binaries in our project. 

Or you could just link our source directory or the handful of individual files into your project. When you update our repo, yours will detect the changes. 

This is basic file management issue. A few links and adjustment to your build scripts will give you what you want. 

If you want to link duplicate submodules:

https://stackoverflow.com/questions/4115817/duplicate-submodules-with-git

https://stackoverflow.com/questions/21077493/how-to-use-submodules-publicly-but-symlinks-to-a-single-clone-locally

**Comment by TokisanGames** [comment]
Closing due to solution provided and no response. All OSes provide the means to link directories.

**Comment by Ughuuu** [comment]
I might be interested in this too. I also have some solution to making it a module without poluting the source code.

**Comment by TokisanGames** [comment]
@Ughuuu Op was asking about making it a git submodule, which is completely different from making it a godot module.
