### ISSUE TITLE
Import multiple (tiled) heightmaps simultaneously

### ISSUE THREAD

**Issue by KMouratidis** [TokisanGames/Terrain3D#320]
### Description

Some software / databases export heightmap data as multiple files, typically following some naming conventions to map position, e.g.: `<X>_<Y>_<pixel size>` (`2672_1227.xyz` or `2672_1227_0.5m.tif` or `x0_y0`), or maybe with start/stop boundaries `<X start>_<X end>_<Y start>_<Y end>` (`4.315_4.456_5.515_5.715`), etc. 

It would be nice if there was a way to point to a directory and import multiple files with a regex or something like that.

**Comment by TokisanGames** [comment]
You could write a script to do it in a few minutes. Open up importer.gd which is a very simple script that uses the C++ API. You should be able to figure it out from there using the basic GDScript API to look at directories and get filenames.

**Comment by KMouratidis** [comment]
Glorious success!

![image](https://github.com/TokisanGames/Terrain3D/assets/26832680/664c0bf8-8adc-4fd4-b551-e22922576c08)

Thanks! It took me a while until I figured out I had to resize my 341x341 images to 1024x1024. I guess because of https://github.com/TokisanGames/Terrain3D/issues/77 the calculated offsets all fell in the same tile and each image overwrote the previous.

Do you think this is relevant for others?

**Comment by TokisanGames** [comment]
Importer.gd does not resize to 1024. The import functions take in any size, smaller or larger than 1024 and automatically pads or slices to regions.
