### ISSUE TITLE
Improve texture scale & rotation

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#322]
### Description

* Rename Texture/`UV Rotation` to `Detiling`
* Add debug views for UV Scale/rotation
* Texture rotation doesn't properly rotate normals. It rotates them like an image rather than a 3D object. This video shows how https://www.youtube.com/watch?v=iXqCszt3LbE

---
Other items completed or tracked elsewhere

Brushing with tools should be able to change only certain features such as:
* ~~Paint UV scale / rotation, but don't change texture~~ Implemented in #365
* ~~Limit painting of color, texture, foliage to texture mask that are already present on the terrain(eg. inspector layers)~~ Duplicate #192

**Comment by Xtarsia** [comment]
I'll take a look.
