### ISSUE TITLE
Support for Godot 3

### ISSUE THREAD

**Issue by SanayRaj** [TokisanGames/Terrain3D#330]
### Description

May of the people are still using godot 3. Because of godot 4 is not running in low end pc. So please add support for godot 3

**Comment by CrayolaEater** [comment]
I think that is impossible at moment. Terrain3D is made in Gdextension that would mean a Gdnative port is needed for the Godot 3 version, which is not doable.

**Comment by TokisanGames** [comment]
Terrain3D definitely won't support Godot 3. You can use the Godot 3 version of https://github.com/Zylann/godot_heightmap_plugin/ or https://github.com/Zylann/godot_voxel or use a custom solution.
