### ISSUE TITLE
Texture jitters when camera moves

### ISSUE THREAD

**Issue by xand00** [TokisanGames/Terrain3D#331]
### Terrain3D version

0.9.1

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated Radeon RX 590 Series (Advanced Micro Devices, Inc.; 31.0.21902.5) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

Black rock texture jitters when camera moves

https://github.com/TokisanGames/Terrain3D/assets/32330527/1053a1fa-c348-4e5d-99f1-4b3c83ddb514

Issue stays while playing game

**Comment by TokisanGames** [comment]
That grey box is a MeshInstance3D with a StandardMaterial, and has nothing to do with Terrain3D. You can delete the Terrain3D node and use this as a basis to file a bug report in the Godot repository. You may have an issue with FSR if you've enabled it, or your video card drivers.

**Comment by xand00** [comment]
> That grey box is a MeshInstance3D with a StandardMaterial, and has nothing to do with Terrain3D. You can delete the Terrain3D node and use this as a basis to file a bug report in the Godot repository. You may have an issue with FSR if you've enabled it, or your video card drivers.

Thanks for the response!

Do you mean setting this one to 0? (FSR Sharpness in Project->Project Settings->Rendering->Scaling 3D)
![image](https://github.com/TokisanGames/Terrain3D/assets/32330527/1693130b-6e38-41c8-8aad-09c1e52e7d0b)

I tried updating my video card drivers and setting FSR Sharpness to 0 (it was 0.2 before), nothing changed, i will report this bug in godot repository

**Comment by TokisanGames** [comment]
Make an MRP without terrain3d. Also try remaking boxes with other textures and narrow down the situations that it occurs in. Look at it under the mobile and compatibility renderers. And search for other tickets so you don't make a duplicate.
