### ISSUE TITLE
Editor tool buttons are tiny on macOS 

### ISSUE THREAD

**Issue by TranquilMarmot** [TokisanGames/Terrain3D#335]
### Terrain3D version

a020a7c1892de46d15598a8d77c6ffa64ceb9283

### System information

Godot v4.2.1.stable - macOS 14.1.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

<img width="606" alt="Screenshot 2024-03-08 at 6 17 38 PM" src="https://github.com/TokisanGames/Terrain3D/assets/504259/d5b3bf49-cfe1-4dce-a5a6-778242d2264a">

On a 2020 M1 Macbook Pro, the editor tool buttons are very small. This is probably because it's a "retina display" and the resolution of the physical screen (2560x1600) is different than the display resolution (1440x900). Somehow the Godot editor deals with this and enlarges icons properly.

**Comment by TokisanGames** [comment]
Is this a duplicate of #288? It probably has nothing to do with Mac, and everything to do with hdpi and editor scale.

**Comment by TranquilMarmot** [comment]
Absolutely a duplicate! Nice call
