### ISSUE TITLE
Godot crashes when saving storage file after using importer.

### ISSUE THREAD

**Issue by axedaddy** [TokisanGames/Terrain3D#339]
### Terrain3D version

v0.9.1

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA RTX A2000 (NVIDIA; 31.0.15.5123) - 12th Gen Intel(R) Core(TM) i7-12700 (20 Threads)

### Is the issue reproducable in the demo?

Not applicable

### Issue description

Godot crashes when saving storage as .res. I'm not seeing this issue with smaller .exr files, this larger one causes the issue. The terrain successfully load's and I can navigate around it in the editor, only when saving storage as a .res does it then crash. Saving as .tres is OK, albeit slow.

note my .exr is 117MB - I'm not able to attach it here due to size limitations.

Steps to reproduce

1. New godot project.
2. open importer.tscn
3. Add my .exr
4. run import
core/variant/variant_utility.cpp:1091 - Terrain3DStorage::import_images: (7168, 12288) image will not fit at (0, 0, 0). Try (-3584, -6144) to center
5. set import position x=-3584, z=-6144
6. run import
7. save storage as, name as .res (see screen shot)
   After about 5sec Godot closes.

![Screenshot 2024-03-15 214518b](https://github.com/TokisanGames/Terrain3D/assets/29943449/821a6acd-4aa7-4db8-9994-7f2d88d0913e)
![Screenshot 2024-03-15 214201](https://github.com/TokisanGames/Terrain3D/assets/29943449/abd3ff64-5e26-4bac-9c70-7e330ca55505)

### Logs

Note: I did attempt to enable logging.  No log file in appdata/roaming/godot,  but I have attached a screen shot of the console.
I can provide the .exr on request (117MB). 

![Screenshot 2024-03-15_godotlog](https://github.com/TokisanGames/Terrain3D/assets/29943449/56a8bb51-a82c-4f35-bfbe-a1e1575b6e15)

**Comment by TokisanGames** [comment]
Duplicate #159
You can import the terrain at runtime without saving. Or use a smaller terrain, eg segments in different scenes. Or wait until Godot fixes the bug.
In the future, crashes that haven't been reported yet should always be tested against the latest nightly build.
