### ISSUE TITLE
Terrain3D not working in Godot 4.2.2

### ISSUE THREAD

**Issue by ksadgum** [TokisanGames/Terrain3D#359]
### Terrain3D version

0.9.2

### System information

Godot 4.2.2

### Is the issue reproducable in the demo?

No

### Issue description

I import the addon to Godot and get a  series of error:
opening the project in the editor at least once.
  core/extension/gdextension.cpp:688 - GDExtension library not found: 
  Failed loading resource: res://addons/terrain_3d/terrain.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  core/extension/gdextension.cpp:688 - GDExtension library not found: 
  Failed loading resource: res://addons/terrain_3d/terrain.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  core/extension/gdextension.cpp:688 - GDExtension library not found: 
  Failed loading resource: res://addons/terrain_3d/terrain.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

**Comment by ksadgum** [comment]
Sorry it was my mistake. Somehow I downloaded the file unfinished. Now it's fixed.

**Comment by TokisanGames** [comment]
Ok.
