### ISSUE TITLE
Moving Terrain3DObjects in tree breaks it

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#390]
### Description

Add a Terrain3DObjects node, possibly as a child of Terrain3D, move it elsewhere and its children objects stop updating. No way to reconnect it except destroy and recreating it.

It should at the least have a reconnect button in the inspector, but better is to reconnect automatically. _enter_tree,  tree_entered, NOTIFICATION_PATH_RENAMED, or the current parent's NOTIFICATION_CHILD_ORDER_CHANGED might be fired during reparenting.

cc: @tcoxon

**Comment by tcoxon** [comment]
@TokisanGames I can take a look at this.
