### ISSUE TITLE
Terrain3DObjects emits gizmo errors & buttons don't work

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#391]
### Description

Selecting a Terrain3DObjects or child node keeps the Terrain3D toolbar open, which is fine.
* Selecting Terrain3D results in the first error. Then selecting another node, results in the second error.
```
 editor/plugins/node_3d_editor_gizmos.cpp:761 - Condition "valid" is true.
 editor/plugins/node_3d_editor_gizmos.cpp:782 - Condition "!valid" is true.
```
* Clicking a Terrain3D tool should reselect the Terrain3D node so it can be used. (which can be done with [plugin.select_terrain()](https://github.com/TokisanGames/Terrain3D/blob/61bebcf1148cee580fe76d586fc41226dcec1356/project/addons/terrain_3d/editor.gd#L288) from my PR #340)

cc: @tcoxon

**Comment by tcoxon** [comment]
@TokisanGames I can take a look at this.
