### ISSUE TITLE
Navmesh generation gets confused when NavigationRegion3D isn't on origin

### ISSUE THREAD

**Issue by Dekker3D** [TokisanGames/Terrain3D#392]
### Terrain3D version

fd5adb0

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.5222) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Is the issue reproducable in the demo?

Not applicable

### Issue description

I was splitting my navigation up into multiple NavigationRegion3Ds, and noticed that they seemed to bake the navmesh wrong for Terrain3D, while it worked fine for normal physics objects. Each region was moved away from the origin as a node, which seemed to cause them to sample the terrain from another area.

When moving the regions back to the scene's origin, and using only the AABB filter region to set their boundaries, the generated navmesh lined up with the actual terrain.

The actual position of the NavigationRegion3D node is probably not correctly applied to the geometry that the Terrain3D provides to the navmesh baker.

(Sorry for the low-effort issue, I already got past this on my project so I'm just noting it for posterity)

**Comment by tcoxon** [comment]
@TokisanGames I can take a look at this.
