### ISSUE TITLE
Smooth tool breaks terrain

### ISSUE THREAD

**Issue by lulasz** [TokisanGames/Terrain3D#396]
### Terrain3D version

v0.9.1-beta 

### System information

Godot v4.2.2.stable.mono

### Is the issue reproducable in the demo?

Yes

### Issue description

When using the **Smooth tool** with **Automatic Regions Disabled** the terrain is getting broken when painting near edges of the terrain. See video.
[Screencast from 2024-06-07 14-11-39.webm](https://github.com/TokisanGames/Terrain3D/assets/4968455/8c6090cc-fe73-4a49-a027-22e69c444289)

![image](https://github.com/TokisanGames/Terrain3D/assets/4968455/3f191f04-83a8-4c1f-8d3e-254dbe3ad5fc)

### Logs
No errors in console/output window

**Comment by TokisanGames** [comment]
Duplicate #336. Already fixed.
