### ISSUE TITLE
Custom Material Shader

### ISSUE THREAD

**Issue by markusstha** [TokisanGames/Terrain3D#404]
### Terrain3D version

v0.9.1

### System information

Godot v4.2 / linux / 6.9.3-arch1-1

### Is the issue reproducable in the demo?

Yes

### Issue description

When trying to create my own shader for my material I always run into the issue that some code is being appended after my code. I tried creating a new empty shader or a visual shader. For example

```
--Main Shader--
    1 | shader_type spatial;
    2 | render_mode blend_mix, depth_draw_opaque, cull_back, diffuse_lambert, specular_schlick_ggx;
    3 | 
    4 | 
    5 | 
    6 | 
    7 | void fragment() {
    8 | 
    9 |  vec4 n_out2p0 = vec4(1.000000, 0.000000, 0.000000, 1.000000);
   10 | 
   11 | 
   12 | 
   13 |  ALBEDO = vec3(n_out2p0.xyz);
   14 | 
   15 | 
   16 |  
E  17->  ALBEDO = color_map.rgb;
   18 |  ROUGHNESS = 0.7;
   19 |  SPECULAR = 0.;
   20 |  NORMAL_MAP = vec3(0.5, 0.5, 1.0);
   21 | 
   22 |  
   23 |  if(bool(texelFetch(_control_maps, get_region_uv(floor(uv)), 0).r >>1u & 0x1u)) {
   24 |  ALBEDO *= vec3(.5, .0, .85);
   25 |  }
   26 | 
   27 | 
   28 | 
   29 | }
   30 |
```

this code was generated by a simple VisualShader which just applies the color red to albedo. Everything from Line 17 on is autogenerated code that references e.g. a colormap, which in my case I didn't provide (I have textures and masks for every pixel). But even it I'd provide the colormap I'd run into an issue in the next lines.

I also tried to use the autogenerated code (~400 lines) and made some changes there, but it seems, changing the ALBEDO like in the example there has no effect (but at least no code is being appended) 

Am I doing this wrong? How do I prevent the auto appending of code?

### Logs

see above

**Comment by TokisanGames** [comment]
The terrain is driven by the shader. If you insert an empty shader, you'll break the terrain. Look in extras for a minimal shader that is everything you need to allow the terrain to function without texturing.

> this code was generated by a simple VisualShader 

VisualShaders aren't supported yet. But not for any reason other the fact that the minimal shader isn't in visual form yet. You could implement it. See #226.

> Everything from Line 17 on is autogenerated code that references 

This code is added when you enable the colormap debug view in the material. All debug views add shader code. The color map debug view is automatically enabled under certain conditions, probably if you have no textures in the asset dock.

> I also tried to use the autogenerated code (~400 lines) and made some changes there, but it seems, changing the ALBEDO like in the example there has no effect (but at least no code is being appended)

Either use the minimal shader and make your own texturing, or work on the default generated shader. If you didn't see changes when modifying ALBEDO, perhaps you did something else wrong. Now that you know this is the correct path, try again and see. Also 0.9.2 is out and better, but this all still applies.

**Comment by markusstha** [comment]
thanks for the detailed response! now that I know how its supposed to work I'll upgrade and have a look again
