### ISSUE TITLE
Brush menu hides as you try to hover it

### ISSUE THREAD

**Issue by tcoxon** [TokisanGames/Terrain3D#405]
### Terrain3D version

main, currently 5f5837542a6fff32d8e60c1cca4760afd2f836f6

### System information

Godot v4.2.2.stable - Arch Linux - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Is the issue reproducable in the demo?

Yes

### Issue description

With the "Raise Terrain" tool I try to change the current brush. Clicking the brush button brings up the menu - but then when the brush button loses hover, the brush menu closes. Because of this, it's not possible to change the brush.

https://github.com/TokisanGames/Terrain3D/assets/165720/4a41bd49-765f-4c9f-89bd-a5c4274376d9

**Comment by TokisanGames** [comment]
Just as I was about to publish.

You can comment out tool_settings.gd:176
	#menu_button.mouse_exited.connect(_on_show_submenu.bind(false, menu_button))

This works pretty well except on the foliage brush when there are a lot of buttons near each other. I'm looking for something else that is safer to exit on.

**Comment by TokisanGames** [comment]
Thanks for the report and cause.
