### ISSUE TITLE
Textures not working after translating a project from pc to mobile.

### ISSUE THREAD

**Issue by Saul2022** [TokisanGames/Terrain3D#406]
### Terrain3D version

0.9.2 build https://github.com/TokisanGames/Terrain3D/actions/runs/9742471492

### System information

Godot 4.3  beta 1  Sansung s23+ Vulkan Mobile

### Is the issue reproducable in the demo?

No

### Issue description

When i tried translatimg my pc project that was on forward + to my phone( because my pc sucks because  it died), everything seemed to go well except for the textures that   looks way  worse in the terrain 3d extension seemingly due to  the texture format(png converted to  etc 2)  as you can see in the first pic( and reimporting them didn"t work) 

One way that i found to fix it  was replacing the textures to ones that  were imported from the mobile file browser to the godot project and assigning them again in the asset dock, which resolved it but sadly suffered a performance hit thx to  android bad drivers and shader complexity( because this phones beat my igpu by  4 times normally ) 

![Screenshot_20240702_123839_Godot Editor 4](https://github.com/TokisanGames/Terrain3D/assets/97898580/11c88b07-a02c-4ed0-92f6-9ee580f2ee55)

![Screenshot_20240702_125833_Godot Editor 4](https://github.com/TokisanGames/Terrain3D/assets/97898580/fa007fe2-2b02-4877-8c6a-b2b3add40d1d)

**Comment by TokisanGames** [comment]
I'm not sure what to tell you as I don't have an android setup, and I don't understand the scenario.

> reproducable in the demo? No

So the demo textures work fine? They are PNG marked with both ETC2 on mobile and on PC, hq so they convert to BPTC.

> the textures that looks way worse in the terrain 3d extension seemingly due to the texture format(png converted to etc 2) as you can see in the first pic( and reimporting them didn"t work)

I don't know what I'm looking at in the first picture. I don't have anything to compare. I see it converted to ETC2_RGBA8 which sounds right, but the image in the inspector looks odd. You explored every option in the Import panel?

> One way that i found to fix it was replacing the textures to ones that were imported from the mobile file browser to the godot project and assigning them again in the asset dock, which resolved it but sadly suffered a performance hit thx to android bad drivers and shader complexity( because this phones beat my igpu by 4 times normally )

I don't understand what exactly you did or found these files, nor what you are saying about the performance hit. 
* What exact files are used in your asset dock resource before and after?
* How do these other files size and format differ from the others? 
* What do they look like in the inspector?
* Do they have different Import settings? 
* What do the .import files look like?
* Can you make other texture files with the same format and size as the ones that cause a performance hit, and use them on a plane in a Godot scene without Terrain3D and experience the same thing?

**Comment by Saul2022** [comment]
Will close this one as it seems to be mostly  my fault on managing my translation and godot mistakes when it reimported the textures on mobile.

**Comment by TokisanGames** [comment]
Ok.

> why didn"t anybody told me that if you hold down a texture from editor dock it automatically opens it inspector

You can double click any texture to show it. [This page](https://terrain3d.readthedocs.io/en/stable/docs/texture_prep.html) mentions it twice. Hold on android is the same as double click.

**Comment by TokisanGames** [comment]
Note [this thread](https://github.com/TokisanGames/Terrain3D/issues/668#issuecomment-4055298663) for mobile users.
