### ISSUE TITLE
Terrain3D is a Node3D, but can not move from origin.

### ISSUE THREAD

**Issue by Dekker3D** [TokisanGames/Terrain3D#429]
### Terrain3D version

v0.9.2-beta

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.5222) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Is the issue reproducable in the demo?

Not applicable

### Issue description

Terrain3D is a Node3D subclass, and one would expect it to be able to move (or rotate or scale). For my own purposes, I would really like to be able to move it, so I can divide my terrain into multiple chunks, and so that I can shift my world around if I want to keep the player near the origin, a common trick when doing really large worlds of any kind.

Currently, Terrain3D seems to ignore all transforms, both when manually trying to move it, or when it's a child of a Node3D that's moved. I can imagine it might be complicated to support rotation or scaling, but just being able to move it laterally would be great!

In a quick search, I couldn't find any other issues about this.

**Comment by TokisanGames** [comment]
Transforms are intentionally disabled. This is not a chunked terrain, it is a clipmap terrain. You can read about all of that in the system architecture doc. 

Even if transforms worked, this system is designed for one terrain node in the tree at any given time. You'll have to find or make another solution if you require terrain chunks, or you can adapt your ideas to a clipmap terrain model.
