### ISSUE TITLE
Foliage instancer fixed/random_angle doesn't work

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#431]
### Description

Both fixed_angle and random_angle only tilt at 0 or ~85 degrees in some circumstances such as in [Kyra's testing](https://discord.com/channels/691957978680786944/1130291534802202735/1265209097318563894) and in Out of the Ashes. However it appears to work fine in the demo.

Also fixed/random_tilt is a better name

**Comment by Xtarsia** [comment]
I was not able to replicate this issue.

**Comment by TokisanGames** [comment]
I cannot in the demo, but it's a definite problem in Out of the Ashes, and the user's project. I haven't figured out the difference yet.

**Comment by TokisanGames** [comment]
The previous build we used from only a week or two ago, tested today, still demonstrated this issue in Out of the Ashes. After renaming the variables in #519 and rebuilding this now works. I reverted the name change and it still works. So perhaps the cause is in cached Godot data. I don't see any issues from the code or testing the data, so will close this.
