### ISSUE TITLE
Add ability to sample the terrain texture outside of the Terrain3D shader

### ISSUE THREAD

**Issue by Smorty10** [TokisanGames/Terrain3D#439]
### Description

Being able to use the terrains texture information outside of the Terrain3D itself would be incredibly useful. This way, blending between terrain and objects would become very easy when using a special shader. This can already be done by applying a simple texture with triplanar projection as seen in this image
![Bildschirmfoto vom 2024-07-29 21-52-44](https://github.com/user-attachments/assets/6eff8690-436e-4235-bcf6-1afa407ef29a)

**Comment by TokisanGames** [comment]
Our Terrain3DMaterial API provides the rid of the material and shader parameters. You should be able to retrieve any of the uniforms such as the texture arrays passed to our shader for your own use via script, in the game or editor. In addition our Terrain3DStorage API provides plenty of other information such as get_texture_id().

Finally, if you want a fully baked texture specifically for blending with objects, you need an RVT. This is a duplicate request. See #245.

**Comment by Smorty10** [comment]
@TokisanGames Was the demo picture for [this release](https://github.com/TokisanGames/Terrain3D/releases/tag/v0.8.4-alpha_gd4.1.3) also done by getting the shader parameters via API?

**Comment by TokisanGames** [comment]
No, that's just a good selection of textures and painting with proper technique, which I discuss in my videos and detail in the texture documentation. There's no RVT blending, which I don't think is a good technique anyway. It's not realistic, and it puts the object into the transparency pipeline which is less performant.

**Comment by Smorty10** [comment]
I see. Then what I am requesting is not necessary. Sorry for the bother.
