### ISSUE TITLE
Add option to disable the de-tiling

### ISSUE THREAD

**Issue by Smorty10** [TokisanGames/Terrain3D#440]
### Description

The detiling can cause heavy performance drops and is currently automatically activated when applying any texture to the terrain. The calculations are being done even if all your textures in the texture list are set to not use texture detiling. It would be great to not have to use the detiling if no textures use it.

**Comment by TokisanGames** [comment]
> The detiling can cause heavy performance drops

Have you tested this theory with our shader? You could test it in a few minutes. You could also disable it yourself, but I think you'll find it is not as expensive as you think.

**Comment by TokisanGames** [comment]
Detiling is already branched off in the shader if its not used. 
https://github.com/TokisanGames/Terrain3D/blob/main/src/shaders/main.glsl#L240

Modern cards spend no time on it if detiling is 0. You can avoid the performance hit by setting all textures to 0. Or customize the shader and remove the code entirely.
