### ISSUE TITLE
Add option to toggle key bindings for Maya

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#441]
### Description

Change ALT+LMB to something else like drag RMB.
Context https://github.com/TokisanGames/Terrain3D/pull/409#issuecomment-2257093148
Code https://github.com/tcoxon/Terrain3D/blob/d616eec395be9fb13c773a472ffd52526e8e717a/project/addons/terrain_3d/src/ui.gd#L403-L408

The setting can go in the menu. Save it to EditorSettings (see assetdock for how).

**Comment by jesus-g20** [comment]
Hi, I am planning to work on this issue. Can I proceed or can I be assigned?

**Comment by TokisanGames** [comment]
Yes, thanks for volunteering. Here are some options for implementation:
* Base
    * Add an Editor Setting "config/Alternate key bindings" that changes ALT+LMB to RMB when enabled. 
    * No gui. 
    * Change the [docs](https://github.com/TokisanGames/Terrain3D/blob/main/doc/docs/user_interface.md) to let people know the option is there.

* Optional Additional
    * In the Terrain3D Menu, make an entry called `Options...`. That dialog box will have the above setting on it (still an Editor Setting in the background), and more in the future. Change the docs to descibe this menu option instead of the editor settings.

**Comment by TokisanGames** [comment]
@jesus-g20 If you can get this in by the next week or two it will go out in the next release.

**Comment by TokisanGames** [comment]
MMB and RMB are occupied for most keymappings. I'm allowing the choice of Alt modifier key. See details here https://github.com/TokisanGames/Terrain3D/pull/509#issuecomment-2426776061.
