### ISSUE TITLE
The "Advanced" button is activated on hover

### ISSUE THREAD

**Issue by JekSun97** [TokisanGames/Terrain3D#443]
### Terrain3D version

v0.9.3-dev

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Is the issue reproducable in the demo?

Not applicable

### Issue description

When you hover over the "Advanced" button, a click signal is emitted even if you don't click the button
![1](https://github.com/user-attachments/assets/da1d28f3-7b4f-450b-858c-e40c34a2fbb9)

### Logs

No

**Comment by JekSun97** [comment]
I just noticed that this happens with the "Brush" button too

**Comment by TokisanGames** [comment]
This is by design. All of the buttons activate on hover. Click the instancer.

**Comment by JekSun97** [comment]
Oh, I didn't know about that.
