### ISSUE TITLE
Godot crashes after starting to paint mesh then pressing Escape and selecting anything in scene

### ISSUE THREAD

**Issue by Radivarig** [TokisanGames/Terrain3D#449]
### Terrain3D version

8a45d61a331fcd8e9c6d8afbc25e278480c3460e

### System information

Godot Engine v4.3.rc3.official.03afb92ef - Windows 11 Home - Vulkan 1.3.278 - Forward+ - NVIDIA GeForce RTX 2070 with Max-Q Design

### Is the issue reproducable in the demo?

Yes

### Issue description

Tested on:
- Terrain3D
    - 0.9.2 (from AssetLib)
    - 0.9.3-dev [nightly build](https://github.com/TokisanGames/Terrain3D/actions/runs/10237771326)
- Godot
    - 4.3-rc2
    - 4.3-rc3

To reproduce:
- Create a terrain and select it
- Go into the `Terrain3D tab > Meshes`
- With the red circle decal showing in the viewport press `Escape`
    - This will throw few errors because during the `ui.gd:264 await get_tree().create_timer(.05).timeout` the `editor.gd:118 _clear` function is called which makes the `plugin.terrain` become null (for which the check was done before the await)

After this trying to select anything in the scene with the blue selection rectangle will crash Godot on mouse release.

However, if the terrain node is selected and then deseleted in the hierarchy, there is no crash.

By searching for `get_deepest_editable_node` I found [this issue](https://github.com/TokisanGames/Terrain3D/issues/395) but the fix for that was  merged into Godot in [4.3-rc2 commits](https://github.com/godotengine/godot/compare/e343dbbcc1030f04dc5833f1c19d267a17332ca9...3978628c6cc1227250fc6ed45c8d854d24c30c30)
> Fix crash when drawing a selection box on an empty scene with certain plugins
> @TokisanGames TokisanGames committed on Jun 20 1780f2840765358b52d8f9bd28a488fd3ef89842

### Logs

```bash
SCRIPT ERROR: Invalid call. Nonexistent function 'get_camera' in base 'Nil'.
    at: update_decal (res://addons/terrain_3d/src/ui.gd:269)
SCRIPT ERROR: Invalid call. Nonexistent function 'get_camera' in base 'Nil'.
    at: update_decal (res://addons/terrain_3d/src/ui.gd:269)
SCRIPT ERROR: Invalid call. Nonexistent function 'get_camera' in base 'Nil'.
    at: update_decal (res://addons/terrain_3d/src/ui.gd:269)
ERROR: Condition "!is_ancestor_of(p_start_node)" is true. Returning: p_start_node
    at: get_deepest_editable_node (scene/main/node.cpp:2525)
WARNING: Terrain3D#3844:_notification: NOTIFICATION_CRASH
    at: push_warning (core/variant/variant_utility.cpp:1112)

================================================================
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
...
[26] error(-1): no debug info in PE/COFF executable
-- END OF BACKTRACE --
================================================================
```

**Comment by TokisanGames** [comment]
Thanks for the detailed report. As you noted that other bug was fixed. Good to know you tested with that fix merged. #395 

Does this occur in the demo in 4.2.2?

Also I didn't think get_camera was called in UI. That same functionality on that line is duplicated in editor.cpp. So it there's at least a few issues going on here. 

https://github.com/TokisanGames/Terrain3D/blob/main/project/addons/terrain_3d/src/ui.gd#L268-L273

**Comment by Radivarig** [comment]
On 4.2.2 there is no crash, although the same error appears when pressing Escape
```bash
ERROR: Condition "!is_ancestor_of(p_start_node)" is true. Returning: p_start_node
   at: get_deepest_editable_node (scene/main/node.cpp:2350)
```

**Comment by TokisanGames** [comment]
Upstream bug report
https://github.com/godotengine/godot/issues/95356

**Comment by TokisanGames** [comment]
Upstream crash and error message fix https://github.com/godotengine/godot/pull/95420

**Comment by TokisanGames** [comment]
Fixed upstream.
