### ISSUE TITLE
cast_to fail

### ISSUE THREAD

**Issue by 28176004** [TokisanGames/Terrain3D#455]
### Terrain3D version

0.9.2

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 32.0.15.5612) - Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 Threads)

### Is the issue reproducable in the demo?

Not applicable

### Issue description

get_node<Terrain3D>("Terrain3D") fail
``` c++
    auto a = get_node<Node>("Terrain3D");      // ok
    auto b = cast_to<Terrain3D>(a);            // fail
    auto c = get_node<Terrain3D>("Terrain3D"); // fail
```
node "Terrain3D" inconvertibility,it is godot-cpp's problem?

**Comment by TokisanGames** [comment]
Please answer my question here: https://github.com/TokisanGames/Terrain3D/issues/452#issuecomment-2283375054

C++ doesn't just fail. It tells you why it doesn't work. What are the messages the compiler gives you?

What compiler and IDE are you using?

Where are your C++ headers? How are you declaring the Terrain3D class?

**Comment by 28176004** [comment]
windows+mingw+vs code,maybe i need msvc

**Comment by 28176004** [comment]
i create a dll ,referenced "terrain.a",and "terrain.a" put in project

**Comment by TokisanGames** [comment]
I need more information to help you. Please answer all of my questions and provide more information. Or send me a simplified project. Any compiler should work fine, but I need to know your setup and compiler messages.

**Comment by 28176004** [comment]
thanks,I didn't use the default build system, maybe 'scons' did more when link library.
i think your code is good.that compile problem.
i want know 'a.dll' reference 'terrain.dll' and godot  reference[ 'a','terrain'] two dlls,it is work?
https://forum.godotengine.org/t/trying-to-build-multiple-gdextentions-lib/67976
some one have seam question.

**Comment by TokisanGames** [comment]
I don't know about 2 libraries. You should focus on one first. This ticket is about casting, and I need more information or a minimum project to help you.

**Comment by 28176004** [comment]
[logistics4.3.zip](https://github.com/user-attachments/files/16609187/logistics4.3.zip)
you right,this is my project

**Comment by TokisanGames** [comment]
> you right,this is my project

Where's the source code? You made two issues expressing problems with C++ connecting to gdextension. There's no C++ code in this project. Send me a minimal C++ project that demonstrates the challenges you are facing.

**Comment by 28176004** [comment]
close problem, This is not an issue pertaining to the library.
