### ISSUE TITLE
Emissive terrain

### ISSUE THREAD

**Issue by aristides86** [TokisanGames/Terrain3D#460]
### Description

We need an option to add emissive terrains, glowing, lava, that kind of business. Maybe it's already here somewhere, but I just can't find it. Ideally to be able to plug in custom terrain shader to be able to manipulate UVs, to show moving surface, for example.

**Comment by TokisanGames** [comment]
Most users don't need it on all the time for all textures. You can add it yourself when needed with a custom shader and texture map. Set your own uniforms to adjust uv scale/offset.

https://terrain3d.readthedocs.io/en/stable/docs/tips.html#add-a-custom-texture-map
