### ISSUE TITLE
Add forest generation

### ISSUE THREAD

**Issue by JekSun97** [TokisanGames/Terrain3D#475]
### Description

I suggest adding tree/forest placement to Terrain3D, most often this tool works together with the terrain.

I have a plugin that is still in development for procedural tree generation, I might try to integrate it into Terrain3D by adding a separate tool that can generate and place forests using a separate resource storing the randomness threshold of tree geometry and their materials, adding HLOD to them, and maybe collision support.

But I would like some help, if it is interesting and makes sense, I could start developing this tool for the next version of Terrain3D.

**Comment by TokisanGames** [comment]
> I suggest adding tree/forest placement to Terrain3D, most often this tool works together with the terrain.

I need more details on what you want. One can already place trees with a particle shader, scatter, or via MMI w/ our foliage instancer. Our instancer has an API already. And more improvements will be coming.

> a separate tool that can generate and place forests

What do you define as a forest? A bunch of trees with variance, placed with a noise map? Or a biome with a variety of trees, shrubs, herbs, and grasses? eg.  https://wrobot.itch.io/jungledemo

> But I would like some help

What do you need? We already provide an API and tutorials to determine where the ground is, its shape, and placement of instances, with more features coming.

**Comment by JekSun97** [comment]
> I need more details on what you want. One can already place trees with a particle shader, scatter, or via MMI w/ our foliage instancer. Our instancer has an API already. And more improvements will be coming.

I want to add a tool for drawing trees on the terrain and tightly integrate it with the modifications of the landscape itself, and it is also possible to add forest generation based on noise, but I can’t yet decide in which area of ​​the interface this would be appropriate.

**Why this should be part of Terrain3D:**
- Trees react to landscape changes (holes, geometry of the terrain?), and be part of regions.
- Unlike shaders, trees will optionally generate collisions or automatic LOD.
- We do not need models for trees, everything is generated procedurally, which will give an absolutely unique forest, combining with Instancer.
- Allows you to create biomes using noise
- A similar tool is integrated into the landscape in Unity, which is also missing in Godot.

> What do you define as a forest? A bunch of trees with variance, placed with a noise map? Or a biome with a variety of trees, shrubs, herbs, and grasses? eg. https://wrobot.itch.io/jungledemo

Both.
It would be possible to add two switches or modes to the Foliage Instancer, one of them would draw with meshes (as it does now), the other would draw forests with its own special settings for tree generation.
It would also be possible to add a new tool to the toolbar, for generating forests using noise.

> We already provide an API and tutorials to determine where the ground is, its shape, and placement of instances, with more features coming.

I haven't delved into the internal Terrain3D API yet, but I hope there won't be any issues with that, I'll be checking it out soon.

If I do have any questions, where can I go to discuss the details?

**Comment by TokisanGames** [comment]
> I want to add a tool for drawing trees on the terrain and tightly integrate it with the modifications of the terrain itself
> Trees react to landscape changes (holes, geometry of the terrain?), and be part of regions.

Foliage already adjusts heights on sculpting and creating holes.

> Unlike shaders, trees will optionally generate collisions or automatic LOD.

Both MMIs and particle shaders can work with generated collision, which I'll be adding. MMIs work with auto generated LODs, I don't know about particle shaders. I'll be adding support for artist created LODs. Are you thinking of something else?

> We do not need models for trees, everything is generated procedurally

Are you going to offer a full range of low poly textures and models up through AAA models and textures? In our game we're using AAA assets. However, asset creation may be out of scope.

> A similar [tool](https://docs.unity3d.com/Manual/terrain-Trees.html) is integrated into the terrain in Unity, which is also missing in Godot.

What is on this list that we haven't already implemented or planned is mass placement (not difficult to add), asset generation, automatic wind (users can already add). Artist lods, collision are coming.

> This stage, related to the interface and its layout, is still in the early stages of ideas.
> If I do have any questions, where can I go to discuss the details?

There are several separate ideas here. If you want some or all to be incorporated in Terrain3D, then the way forward is to pick one, and provide a design to be discussed before being implemented. That can be documented here in this issue, or a github discussion. You can also chat on our discord server.

I can't accept a large module all at once. I need smaller pieces that expand the existing infrastructure, which can build towards something. I also don't want two systems that do the same functionality eg lod.

You have read through #43, right?
