### ISSUE TITLE
Spray w/ auto direction overwrites the direction of base texture

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#481]
### Description

Spraying with auto direction overwrites the direction on the base layer below. Spray should only change direction on the Spray pixels (where brush_alpha >. 1), I think. Due to blending, it might not work as we imagine. Might have to bump the threshold up to 0.3 or so. 

https://discord.com/channels/691957978680786944/1065519581013229578/1275318563149840437

**Comment by Xtarsia** [comment]
I think the condition for allowing spray to write angle/scale should require that the blend value that will be written to the control map, be 84 (1/3rd of 255)
