### ISSUE TITLE
HTML WebGL support

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#502]
### Description

#500 and #512 brought support for the compatibility renderer and the webgl export. Early testing without threads has provided a working HTML export. Here is the process so far. 

A key point is that the **terrain build**, **the export template**, and **export settings** must match the same thread support with all three marked on or off.

### Docs
Building instructions
https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_web.html

Godot Export for web docs
https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html

### Building

**Unthreaded Web builds and terrain.gdextension updates have now been included in the main branch CI.**

Use 4.3 or higher.

To build the extension for web you must install emscripten, set up the build environment, then build the web assembly version. I installed with scoop, which is how my python is also installed, per the Godot building instructions. 

Emscripten seems to be very finicky about versions. [Akien reports](https://github.com/godotengine/godot/issues/82865#issuecomment-2275344596) they are using v3.1.64 for 4.3 stable builds.

```
$ scoop install emscripten@3.1.64

# then I restarted my terminal to get the updated path to finish installing emscripten

$ emsdk install 3.1.64
$ emsdk activate 3.1.64

# finally setup the build environment
$ source ~/scoop/apps/emscripten/current/emsdk_env.sh

# build
$ scons platform=web target=template_debug threads=no

$ ls project/addons/terrain_3d/bin/*.wasm
project/addons/terrain_3d/bin/libterrain.web.debug.wasm32.wasm
```

This file needs to be added to `terrain.gdextension`:
```
web = "res://addons/terrain_3d/bin/libterrain.web.debug.wasm32.wasm"

or 

web.debug = "res://addons/terrain_3d/bin/libterrain.web.debug.wasm32.wasm"
web.release = "res://addons/terrain_3d/bin/libterrain.web.release.wasm32.wasm"

Untested possibilities:
web.wasm32.nothreads = "res://addons/terrain_3d/bin/libterrain.web.debug.wasm32.nothreads.wasm"
web.debug.wasm32.nothreads = "res://addons/terrain_3d/bin/libterrain.web.debug.wasm32.nothreads.wasm"
```

### Project Setup
* The renderer must be set to Compatibility.

* Textures must be imported `VRAM Uncompressed` in 4.3. The new decompression PR is insufficient.

* Create an override shader with the following changes:
```
@@ -44,7 +44,7 @@
 uniform int _region_map[1024];
 uniform vec2 _region_locations[1024];
 uniform highp sampler2DArray _height_maps : repeat_disable;
-uniform highp usampler2DArray _control_maps : repeat_disable;
+uniform highp sampler2DArray _control_maps : repeat_disable;
 uniform highp sampler2DArray _color_maps : source_color, filter_linear_mipmap_anisotropic, repeat_disable;
 uniform highp sampler2DArray _texture_array_albedo : source_color, filter_linear_mipmap_anisotropic, repeat_enable;
 uniform highp sampler2DArray _texture_array_normal : hint_normal, filter_linear_mipmap_anisotropic, repeat_enable;
@@ -255,7 +255,7 @@

        // Discard vertices for Holes. 1 lookup
        v_region = get_region_uv(UV);
-       uint control = texelFetch(_control_maps, v_region, 0).r;
+       uint control = floatBitsToUint(texelFetch(_control_maps, v_region, 0).r);
        bool hole = bool(control >>2u & 0x1u);

        // Show holes to all cameras except mouse camera (on exactly 1 layer)
@@ -525,10 +525,10 @@

        // Lookup adjacent vertices. 4 lookups
        uint control[4] = {
-               texelFetch(_control_maps, indexUV[0], 0).r,
-               texelFetch(_control_maps, indexUV[1], 0).r,
-               texelFetch(_control_maps, indexUV[2], 0).r,
-               texelFetch(_control_maps, indexUV[3], 0).r
+               floatBitsToUint(texelFetch(_control_maps, indexUV[0], 0).r),
+               floatBitsToUint(texelFetch(_control_maps, indexUV[1], 0).r),
+               floatBitsToUint(texelFetch(_control_maps, indexUV[2], 0).r),
+               floatBitsToUint(texelFetch(_control_maps, indexUV[3], 0).r)
        };

        // Get the textures for each vertex. 8-16 lookups (2-4 ea)
```

* For the demo, Esc doesn't work, so in UI.gd, allow backtick to be used:
```
-            KEY_ESCAPE:
+            KEY_ESCAPE, KEY_QUOTELEFT:
```

### Exporting

* Select custom template debug: [web_dlink_nothreads_debug.zip](https://forum.godotengine.org/t/gdextension-not-loading-in-web-export/81867/5), which I found here: `C:/Users/Cory/AppData/Roaming/Godot/export_templates/4.3.stable/web_dlink_nothreads_debug.zip`
* Enable `Extensions Support`
* Ensure `Threads Support` is disabled to match the other settings

### Upload to Webserver
* After export, the full package must be uploaded to a webserver. Itch or your own. That server must be configured with **SharedArrayBuffer** & **Cross Origin Isolation**.

* In nginx this can be enabled with:
```
    location ^~ /terrain3d/ {
        add_header "Cross-Origin-Opener-Policy" "same-origin";
        add_header "Cross-Origin-Embedder-Policy" "require-corp";
    }

```

* On Itch.io , edit game, find the Embed Options section and enable:

`SharedArrayBuffer support - (Experimental) This may break parts of the page or your project. Only enable if you know you need it.`

### Running

On my Win11/64, RTX3070, when I run it on Edge 131.0.2903.112, I get 1fps. When run on Chrome 131.0.6778.205, I get 50fps and no artifacts. Everything works fine on chrome. It's likely Edge needs a setting change.

Test it here:
https://tokisan.com/terrain3d_demo/demo.html

**Comment by Xtarsia** [comment]
for refrence, this project is a working example of GDextension exported to web, and is under MIT

https://github.com/kiwijuice56/sand-slide - working example in chrome browser in itch.io too!

**Comment by TokisanGames** [comment]
Ok, I have the demo *scene* building and loading. Updated instructions in Op. 

https://tokisan.com/terrain3d/demo.html

However there are three problems:
* The mouse isn't captured, so the camera doesn't move (but the mouse wheel does work)
* Terrain collision doesn't work. But it works on the tunnel.
* The terrain doesn't render. The console reports a problem with shader compilation:
```
 USER ERROR: SceneShaderGLES3: Vertex shader compilation failed:
 ERROR: 0:460: 'usampler2DArray' : No precision specified
 WARNING: 0:718: '/' : Zero divided by zero during constant folding generated NaN
 
    at: _display_error_with_code (drivers/gles3/shader_gles3.cpp:254)
 USER ERROR: Method/function failed.
    at: _compile_specialization (drivers/gles3/shader_gles3.cpp:348)
```

**Comment by TokisanGames** [comment]
New url. Back tick \` will also capture the mouse, and arrow keys will turn the camera.
https://tokisan.com/terrain3d_demo/demo.html

It seems that all the samplers need highp. Including those in uniforms.glsl.

Here's the full console log, after adding additional highps:
[console_log.txt](https://github.com/user-attachments/files/17179088/console_log.txt)


The last remaining shader error is:
```
demo.js:474  ERROR: 0:528: '[' : array index for samplers must be constant integral expressions
also 535, 536.
```

These lines are:
```
demo.js:459 528: 			vec2 m_decal_uv=(((vec2(((m_cosa * m_uv.x) - (m_sina * m_uv.y)), ((m_sina * m_uv.x) + (m_cosa * m_uv.y))) - (vec2(((m_cosa * m_dus_editor_decal_position[m_i].x) - (m_sina * m_dus_editor_decal_position[m_i].y)), ((m_sina * m_dus_editor_decal_position[m_i].x) + (m_cosa * m_dus_editor_decal_position[m_i].y))) * m_dus_vertex_density)) * m_size) * m_dus_vertex_spacing);

demo.js:459 535: 			float m_decal=smoothstep(0.10000000149012, 1.0, texture(m_dus_editor_decal[m_i], (m_decal_uv + 0.5)).r);
demo.js:459 536: 			m_albedo=mix(m_albedo, m_dus_editor_decal_color[m_i].rgb, (m_decal * m_dus_editor_decal_color[m_i].a));
```

I'm not sure why webgl doesn't like these array indices compared to our other array indices.

> texture(m_dus_editor_decal[m_i], (m_decal_uv + 0.5)).r`

I think this should be `texture(_editor_decal, vec3(decal_uv + 0.5, float(i)))`. In my own custom shader, accessing an array index this way was working, but when I put this into the glsl file and compiled, Godot reports this in the desktop. Didn't try webgl yet:
`SHADER ERROR: Invalid arguments for the built-in function: "texture(sampler2D[3],vec3)".`

**Comment by TokisanGames** [comment]
Alright, next error is 256 instances of this before it stops:
```
GL_INVALID_OPERATION: Mismatch between texture format and sampler type (signed/unsigned/float/shadow).
WebGL: too many errors, no more errors will be reported to the console for this context.
```

I changed controlmap to sampler2DArray and put in floatBitsToUint() around the calls. However that didn't fix it or change the number of errors. I don't have any shader dumps or identification as to what line it doesn't like.

**Comment by Xtarsia** [comment]
did you catch all 5 instances of the control map reads?

**Comment by TokisanGames** [comment]
No, I have 7 instances. 5 in main, 1 editor functions, 1 debug views. Worked on desktop.

**Comment by Xtarsia** [comment]
theres actually a few more in debug views now you mention that, but those shouldnt cause problems unless they are on.

**Comment by TokisanGames** [comment]
I have it rendering something now. 

https://tokisan.com/terrain3d_demo/demo.html

![{A5AE0F17-FE72-4E99-95EB-C272633D455C}](https://github.com/user-attachments/assets/1a3d0250-ad82-40cf-bd85-07ebe44310f4)

This is using the minimum shader with a gradient color applied.

Albedo is only blue. These grey spots appear only near the camera, and they are usually constantly moving around, even when the camera is still. But at some angles they are still.

Removing source_color from the mouse depth didn't help

Just highp with a usampler didn't work. This needed highp and sampler/floatbitstouint.

Holes work surprisingly. I thought it complained about dividing by 0 before, but it doesn't care about it now.

Here's my working [minimum.txt](https://github.com/user-attachments/files/17241035/minimum.txt) shader.

This [full_shader.txt](https://github.com/user-attachments/files/17241052/full_shader.txt)
 produces the errors noted [above](https://github.com/TokisanGames/Terrain3D/issues/502#issuecomment-2381440737).

**Comment by TokisanGames** [comment]
![image](https://github.com/user-attachments/assets/beaf33c2-cbd5-44e3-a7ee-94efa3b97eea)

This version of the full shader works. [working_shader.txt](https://github.com/user-attachments/files/17241271/working_shader.txt)

**Comment by TokisanGames** [comment]
#512 has a working web build. Now I don't get any grey artifacts with the same setup, but building with CI. On chrome I get 45-60fps, on edge I get only 1fps. Previously I had 45-60fps on edge with artifacts.

**Comment by FeralBytes** [comment]
@TokisanGames When you have time. I was wondering if there will be support for Web builds with Threads enabled to be added to the automated builds, or was there additional problems that are blocking threaded web builds? Thank you for this awesome addition to Godot!

**Comment by TokisanGames** [comment]
Web builds are experimental and not supported now until they are better supported in godot and browsers. I'm not going to spend much time on it now. However you're welcome to expand the testing and development. Do threaded builds work? I'll accept a PR and testing.

**Comment by FeralBytes** [comment]
I totally understand your stance. I also understand that your primary focus is and as it should be your game which is not a web build. The fact that experimental web support is now a thing is great. I was just curious if you had tried doing a threaded build and if so, if you remember any specific problems that you had encountered, as it would inform any efforts by me. If I have time I will test a threaded build and if it does work I will push a PR. Again thank you for your time.
