### ISSUE TITLE
Expose texture type(base and overlay) by global position just like height

### ISSUE THREAD

**Issue by omercemcicekli** [TokisanGames/Terrain3D#504]
### Description

It might be a good idea to expose texture by global position to detect what kind of texture it is to play sounds accordingly (mud, grass, sands, etc.). Feel free to correct my proposal if there is a way to do this with the current API. 

Thanks.

**Comment by TokisanGames** [comment]
https://terrain3d.readthedocs.io/en/stable/api/class_terrain3dstorage.html#class-terrain3dstorage-method-get-texture-id
