### ISSUE TITLE
Move everything to GDExtension

### ISSUE THREAD

**Issue by outobugi** [TokisanGames/Terrain3D#51]
UI, icons, brushes etc.

GDScript is currently used here only because GDExtension has problems with EditorPlugins. Once those problems are gone, we can convert everything to C++. For the transition to be painless as possible, the UI must done in script.

**Comment by Difint** [comment]
Hey, you've made really an interesting project!

However may I suggest to leave most of the UI in the GDScript, while using CPP code for low-level calculations only? It'll make it easier to create new tools without recompiling cpp which is quite inconvinient

**Comment by TokisanGames** [comment]
I have no plans to implement this idea. Managing the UI layout through GDScript and scenes is far more convenient than C++. I see no benefit to offering a single, self contained library with everything inside over a library with a bunch of files used in the editor only, especially at the cost of development.
