### ISSUE TITLE
Spray Overlay Texture

### ISSUE THREAD

**Issue by KN16H70WL** [TokisanGames/Terrain3D#530]
### Terrain3D version

v0.9.2

### System information

Godot v4.3

### Is the issue reproducable in the demo?

Not applicable

### Issue description

For some reason the Spray Overlay Texture tool does absolutely nothing. I have checked the Auto Shader and it is of in that area, i painted the base texture and that worked. But when using the Spray Overlay Texture to blend the edges of the path into the grass, as shown on the tutorial video, it does nothing. I dont know if I am doing something wrong or if there is an issue.

**Comment by TokisanGames** [comment]
As we discussed on discord, ensure your textures have heights in mid range. It works fine with a proper setup. Use a nightly build in main or 0.9.3 for testing as the brush has already been improved.

Closing this, but can reopen if there's a further problem on the latest version.
