### ISSUE TITLE
Terrain3DObjects: Undo after sculpt operation does not move object (until next sculpt operation)

### ISSUE THREAD

**Issue by benjiwolff** [TokisanGames/Terrain3D#539]
### Terrain3D version

v0.9.3

### System information

macOS 14.5, Godot 4.3

### Is the issue reproducable in the demo?

Yes

### Issue description

When a sculpting operation is undone (ctrl+z), the objects under a Terrain3DObject do not move back to the position they were in before the sculpting operation. Only with the next sculpting operation the object is moved back to the original offset.

**Comment by TokisanGames** [comment]
Thanks for the report. Fixed in #540
