### ISSUE TITLE
Pack textures dialog layout is broken

### ISSUE THREAD

**Issue by abegong** [TokisanGames/Terrain3D#543]
### Terrain3D version

v0.9.3

### System information

Godot 4.3.stable - MacOs Ventura 13.4.1 (c) 

### Is the issue reproducable in the demo?

Not applicable

### Issue description

When I click "Pack Textures" to open the Channel Packer dialog, the dialog layout is messed up.

<img width="344" alt="Screenshot 2024-11-05 at 7 11 58 PM" src="https://github.com/user-attachments/assets/5c670af6-7e2c-474c-ac22-b54c750e94bd">

(I haven't specifically replicated this with the demo, but it doesn't seem like that should matter.)

**Comment by abegong** [comment]
Also, thanks for making this plugin. Amazing tool!

**Comment by abegong** [comment]
Yes, it looks like it is

**Comment by TokisanGames** [comment]
Closing in favor of #531
