### ISSUE TITLE
Change to meta_or_ctrl for macos

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#549]
### Description

On Macos ctrl+click is right-click and cannot be changed.

Instead change input detection to use `Input.is_command_or_control_pressed()`. Then the commands will be inverse: ctrl/cmd, alt mode: alt/option/keybind.

In the meantime, macos users can inverse by first clicking and holding, then pressing ctrl.

**Comment by matpersonne** [comment]
Hello, Yes for me it's totally impossible to remove region with ctrl + LMB (trackpad) MacOs

**Comment by TokisanGames** [comment]
Click+hold first, then press ctrl. Also sculpting and painting on a trackpad is extremely difficult anyway. I recommend getting an external mouse or tablet.

**Comment by TokisanGames** [comment]
The recommendation for an external mouse is for general sculpting, independent of this issue. Ctrl+click won't work on any input device until we can replace the key in code. Click+hold first, then pressing ctrl is the only way to get removal to work on a mac at the moment.

**Comment by TokisanGames** [comment]
Fixed by #568. Would still like testers of the above comment and/or #568.

**Comment by henriknh** [comment]
Hey! Thank you for looking into this! I tested this now on my MacBook Pro M2 15.1.1 now on 0.9.3a and i found the above line at 276 instead.
If I move the mouse around the brush is white and when I left click the terrain is raised, as expected.
If I press and hold _cmd_ and move the mouse around the brush is black instead and when I left click the terrain is lowered, so this seems to fix the issue!

**Comment by TokisanGames** [comment]
Thanks for the report. The fix has been merged in to main which is usable in nightly builds, but you can continue using this manual fix in the current version.
