### ISSUE TITLE
Take a look at Rendering layers for both Terrain and Foliage

### ISSUE THREAD

**Issue by skribbbly** [TokisanGames/Terrain3D#550]
### Terrain3D version

v0.9.0

### System information

Godot4.2+

### Is the issue reproducable in the demo?

Yes

### Issue description

In terms of Render layers for Terrain, Render layers have no effect as to what light source the terrain is being affected by, as long as the terrain has a render layer, it will be affected by any light source, regardless of layer. I believe this is a universal issue for any version of Godot, as I've experienced it with both 4.2 and 4.3.

As for Foliage, Cory [Tokisan] told me to add this to the issue when attempting to assist me.

**Comment by martingu11** [comment]
Glad to see this reported, I've just run into the same issue and was wondering what am I doing wrong. Kind of breaks my lighting setup right now. I'll try to manage just with one main light but it would be awesome to get this fixed!

**Comment by TheOrioli** [comment]
The problem is that the light cull mask doesn't expose all the render layer bits.
You need to turn off bit 31 on the light because Terrain3D uses it for mouse position detection
https://terrain3d.readthedocs.io/en/latest/api/class_terrain3d.html#class-terrain3d-property-render-layers

Unfortunately that will require an extra tool script.

Pulled this out thing air just now so might be bugged:
```gdscript
@tool
extends OmniLight3D

func _ready() -> void:
	light_cull_mask = light_cull_mask & ~(1 << 31)
```

**Comment by TokisanGames** [comment]
Indeed, @TheOrioli has it correct.

Render layers work fine for lights on terrain. 

By default, the terrain renders on both the settable layers Terrain3D.render_layers and Terrain3D.mouse_layer.

Lights have a default light_cull_mask of all 32 layers on (0xFFFFFFFF). The editor inspector only shows layers 1-20 and has layers 21-32 reserved for editor plugins per the documentation. There's no way to turn off 21-32 in the editor, which should be changed by the engine devs. So the light is rendering on the mouse layer.

Building on the script above, you could attach this to your lights. Being a tool script it's usable in editor. Just click zero_mask to clear the cull mask including the reserved bits, then set the layers you want. You could even give this a specific extends (eg DirectionalLight3D) and a class_name and it will show up in Create New Node so you can instantly add it with the script attached.

```
@tool
extends Light3D

@export var zero_mask: bool = false :
	set(value):
		light_cull_mask = 0
```
