### ISSUE TITLE
[Feature Request] Road/Path Drawing Tool

### ISSUE THREAD

**Issue by JekSun97** [TokisanGames/Terrain3D#558]
### Description

The plugin is seriously lacking a tool that would allow us to draw roads, rivers, paths, with shape changes in real time. Today I saw that this function has been [added to MTerrain](https://www.youtube.com/watch?v=s1s1zdTGliQ&ab_channel=mohsenzare), which is really lacking in Terrain3D.

There are many plugins that generate roads or rivers, but I would like to paint with a texture of stones on the grass, and not generate a mesh

**Comment by TokisanGames** [comment]
Duplicate #129, #280.
Currently paths can easily be created destructively with the height brush or the slope brush.
