### ISSUE TITLE
How can I modify this terrain or its transform, such as position? If terrain3D cannot achieve it, are there any other recommended solutions? thank you!

### ISSUE THREAD

**Issue by baiduwen3** [TokisanGames/Terrain3D#571]
### Description

How can I modify this terrain or its transform, such as position? If terrain3D cannot achieve it, are there any other recommended solutions? thank you!

**Comment by TokisanGames** [comment]
The terrain is modifiable with the sculpting tools. Transforms are disabled for various technical reasons. You can move data by either renaming the region files and reloading, or exporting and reimporting data where you want it.
