### ISSUE TITLE
"Add Regions While Sculpting" Not work with the height brush

### ISSUE THREAD

**Issue by zedrun00** [TokisanGames/Terrain3D#572]
### Terrain3D version

master

### System information

godot4.3

### Is the issue reproducable in the demo?

Yes

### Issue description

https://github.com/user-attachments/assets/3f484cc0-98c6-4e5b-9893-ccb74c75393e

**Comment by TokisanGames** [comment]
Thanks, fixed in d606879b08b52304ebb7225f2a6b47349aeb78a5
