### ISSUE TITLE
Edgy/Blocky Textures

### ISSUE THREAD

**Issue by onuryavuzmeral** [TokisanGames/Terrain3D#573]
### Terrain3D version

v0.9.3a

### System information

Godot v4.3 Mobile

### Is the issue reproducable in the demo?

Not applicable

### Issue description

Hello,

I couldn't get a smooth transition between textures.
My Workflow is :
1- Disable Auto Shader where you want to manually paint.
2- Paint Base texture tool. (grass)
3- Use spray tool to add other textures. (sand)

![Screenshot 2024-12-11 143449](https://github.com/user-attachments/assets/84ee88b4-8eac-47d9-b94f-981a6aae63d2)

Thanks,

**Comment by TokisanGames** [comment]
Can you reproduce it in the demo with the mobile renderer?
Works fine for me.

![{8D28DDDA-86F7-492D-A107-43A27C95E504}](https://github.com/user-attachments/assets/9551872f-c9d2-49e9-b859-94668c698f75)

You need to have height textures and proper technique. Paint BOTH textures. Then use Spray to blend.
https://terrain3d.readthedocs.io/en/stable/docs/texture_painting.html#manual-painting-technique

**Comment by onuryavuzmeral** [comment]
Below are some debugging. Hope it helps.
Textured
![Screenshot 2024-12-11 183923](https://github.com/user-attachments/assets/71a8e4d2-9dd9-41e7-ad1c-e33223f99491)
Debug control texture
![Screenshot 2024-12-11 183938](https://github.com/user-attachments/assets/c389716b-fe71-4f03-906f-0daf893a7d20)
Debug control blend
![Screenshot 2024-12-11 183945](https://github.com/user-attachments/assets/b3f14652-4de2-46e9-b271-33d63d0005ee)
Debug control blend from demo scene
![Screenshot 2024-12-11 184730](https://github.com/user-attachments/assets/2d6f70ac-44ab-4e27-ba46-cbf53ecc4365)
