### ISSUE TITLE
Textures disappear/display unknown grid after adding a second texture to the Terrain3D texture list

### ISSUE THREAD

**Issue by Randoree** [TokisanGames/Terrain3D#577]
### Terrain3D version

v 0.9.3a

### System information

Godot v4.3.stable / Vulkan Forward+ / Windows 10 / 3070Ti, I5 12400f

### Is the issue reproducable in the demo?

Yes

### Issue description

If i add a texture to a Terrain3D, it displays properly. However, when a second texture is added to the list, all textures visually disappear, leaving a large white "unknown" texture. If the second texture is removed, the first one reappears but displays visible lines along its edges, creating a grid-like pattern on the terrain. These lines are noticeable during runtime but only from a distance (they vanish as the camera moves closer). 

The white "unknown" texture visual issue seems to not occur when both textures have the same "DTX" version or when both are the same file. However i have found no explanation for the lines issue.

This issue is consistently reproducible in the demo.

https://github.com/user-attachments/assets/8d39be08-9fd6-4d7f-8c51-90e5b8f02a90

https://github.com/user-attachments/assets/7cb626dd-1753-4ca0-b8ee-e9648a26ab71

**Comment by TokisanGames** [comment]
> However, when a second texture is added to the list, all textures visually disappear, leaving a large white "unknown" texture. 

Your console tells you the second texture does not have the same size or format as the first one. Review the requirements in the texture setup documentation.

> If the second texture is removed, the first one reappears but displays visible lines along its edges, creating a grid-like pattern on the terrain. These lines are noticeable during runtime but only from a distance (they vanish as the camera moves closer).

You've probably messed up your generated texture array by putting in incompatible textures. You can probably rebuild it by changing scenes, or adding a properly setup texture, or removing the first and readding it, or adjusting any of the texture asset settings.

**Comment by Randoree** [comment]
Using the same format helped whith that white texture issue, thank you ! However changing scenes and using compatible textures did not solve my grid problem, even after setting it in a new project.
![image](https://github.com/user-attachments/assets/c0241c2a-5668-454a-a4c0-3e96c457bdfa)

**Comment by TokisanGames** [comment]
When exactly does the black grid appear? e.g. how many textures, when applied on ground? 
If you add more textures does it change? 
Is it there if the textures are in the asset dock but not on the ground? 
The black lines are different widths. What caused that? Texture size, uv scale, camera angle, painted scale?
Does it appear with Manual or auto shading?
Does it change by camera angle?
Does it appear on any of the material/debug views?
Do they appear in the demo with the demo textures?
Are you using the default shader?
What does the inspector report your textures as when you double click them?
What is the date of your video card driver?

**Comment by Randoree** [comment]
I might have fixed my issue by re-exporting my textures sizes as 1024 * 1024, my previous texture was 1920 * 1080 because i read that a power of two texture was recommended but not required.


Nevertheless, here is what happened with the 1920*1080 texture for the record, thanks again :



-Adding a first texture with **mipmaps imported** will display the grid. This grid will also affect further textures added to the list.

-If the textures have **no imported mipmaps**, _the grid will not appear on the last texture in the list but will affect all the previous ones_. For example:

- If there are 4 textures in the list, only the first 3 will be affected.

- If there is only a single texture in the list, it will not be affected, as it is considered the last texture i guess.

- The grid wont disappear if you remove the current last texture but will disappear if you re-add it. 

see below :

![image](https://github.com/user-attachments/assets/28532756-26d1-4205-85f5-068cb6df1a32)

- The lines do appear if the textures remain in the asset dock 

- The lines width changes with both UV Scale and Painted Scale.

- The lines appear in both Manual and Autoshading.

- In the editor, moving the camera either far away or extremely close to the textures causes the lines to disappear. However, during runtime, moving the camera far away does not make the lines disappear, but getting extremely close to them does.

![image](https://github.com/user-attachments/assets/85b36f31-b1b5-417c-8e79-a57d0f62e071)
![image](https://github.com/user-attachments/assets/568311bb-db08-4a0a-9aea-494335f56f70)

-It does not appear in the material view and debug views except for Autoshader, Navigation, Texture Height/Normal/Rough and the grids.

-They do not appear with the demo textures

-I was using the default shader

-The editor reports them as CompressedTexture2D and my latest video card driver my 4 days old

**Comment by TokisanGames** [comment]
> I might have fixed my issue by re-exporting my textures sizes as 1024 * 1024, my previous texture was 1920 * 1080 because i read that a power of two texture was recommended but not required.

Power of 2 means 256x256, 512x512, 1024x1024. Not non-square textures. You could use 1000x1000 and be fine. Non-square use is rare, usually for special cases like 2:1 on a tree trunk. Never 16:9 or odd aspect ratios. It's unrestricted so you can use whatever textures you want, but garbage in = garbage out. As a beginner, you should only use square, seamless, power of 2 textures.

> In the editor, moving the camera either far away or extremely close to the textures causes the lines to disappear. However, during runtime, moving the camera far away does not make the lines disappear, but getting extremely close to them does.

You messed up your mipmaps by using non-square textures. Godot padded the mipmaps with black when it generated them. Nothing to do with Terrain3D. This is how 3D engines, and specifically Godot works.
