### ISSUE TITLE
Channel packer recommendation

### ISSUE THREAD

**Issue by catprisbrey** [TokisanGames/Terrain3D#579]
UPDATE: I misread the documentation. I see it says you can pack in-app. So good! Nevermind then! I had still be only reading the documentation and I structions and hadn't launched the plugin yet... Hmm, I was about to close/delete this issue but I'll leave it in case you still think my applet BackPacker could be useful for users, but honestly it sounds like it's already covered. 

### Description

I was about to start using your tool and I saw that you need to pack the textures in a specific way, And I realized that can be quite difficult for a lot of users, and your documentation only touches on it lightly. 

I wanted to offer either assistance or just reference to a tool I wrote in Godot, with the idea perhaps this could be implemented somehow within your tool too? The tool i wrote a few years back called backpacker, which uses the graph editor to let you mix and match texture files to pack anyway you need in a very intuitive way. So something like this might be useful to embed within your tool, or provide something similar, or even just reference in your documentation if you think it'll make the work easier for your users. I'll share a link and a gif if I can here. 

https://felesmachina.itch.io/backpacker

https://img.itch.zone/aW1hZ2UvMjIzMjg1Ny8xMzIyMDM5MS5naWY=/original/ocecgF.gif

![ocecgF](https://github.com/user-attachments/assets/74ef9541-976d-44d8-93e3-0ecdc2028cd0)

**Comment by TokisanGames** [comment]
Thanks for the note. Our built in channel packer is adequate, but it provides some necessary features like inverting normals, smoothness to roughness, and orthonormalizing the normal map. If you continue to use Terrain3D and want to contribute, the channel packer and other UI elements can use improvement. See #81
