### ISSUE TITLE
can't pack textures on MacOS with Godot 4.3

### ISSUE THREAD

**Issue by EsotericShadow** [TokisanGames/Terrain3D#586]
### Terrain3D version

v0.93

### System information

Godot 4.3, Mac OS Monterey V12.7.6, 2.2 GHz Quad-Core Intel Core i7.

### Is the issue reproducable in the demo?

Not applicable

### Issue description

the UI for packing textures is all jumbled, possibly make it resizable or scan to fit screen resolution? my Mac is 15.4-inch (2880 × 1800)

<img width="1381" alt="Screen Shot 2024-12-29 at 6 01 54 PM" src="https://github.com/user-attachments/assets/575d0093-7a57-4d2d-839d-d75db5b0c97a" />

**Comment by TokisanGames** [comment]
Was fixed a while ago. Use a nightly build or disable hdpi.

Duplicate #531
