### ISSUE TITLE
Implement Slope Sculpting Tool 

### ISSUE THREAD

**Issue by TokisanGames** [TokisanGames/Terrain3D#96]
This issue is for sculpting a slope. This should be a tool. For painting textures by slope, see #282

Brush Slope does nothing and was hidden in 283767e1162e558f4f32bb1037014a08507406e8, merged in #91.

Implement it.

**Comment by tcoxon** [comment]
It's looking like I'll need this tool for my project. Do you have a particular idea in mind for how it would work? If our needs align, I could consider implementing & contributing it.

Something like the flatten tool, where you pick a starting height, then click and drag, with the difference being the further you drag from your starting point, the lower the height gets, according to an angle setting?

**Comment by TokisanGames** [comment]
I think there are two implementations of `slope`. I'll take PRs for either or both.

1) Slope when applying textures and color, painting only on flat surfaces or only on slopes.

2) Slope height brush: Select starting point, Select ending point, and it automatically creates a grade between them in the general shape and size of the current brush.

Starting/ending elevations can be predefined with the other brushes. 

I've found when brushing heights that I need a slope to connect between a higher area and a lower area. I don't think I've ever needed an arbitrary length brush. Have you found differently? Where you want to start making a grade without a destination in mind?

**Comment by tcoxon** [comment]
> Have you found differently? Where you want to start making a grade without a destination in mind?

We're only just in the process of initially blocking out terrain. In our case, the destination doesn't matter too much because almost all space is unused. And it can be useful to guarantee a particular angle to the slope to ensure navigability. But I _can_ see that if you've already got a lot of stuff on your terrain that you want to keep, it makes sense to need a particular end point.

Do you see slope height brush as being:
1. Drag from starting point to ending point. Then when you release the mouse button, it modifies the terrain with a slope between them in a straight line from start to end.
2. Or click starting point, click ending point, then click and drag out a potentially wavy line between the two, modifying terrain as the mouse moves?

**Comment by TokisanGames** [comment]
What I envision is a simple: Click start, click end, straight slope is created. No drag. 

However, if you want to do # 2, click start, click end, then it becomes drawable with height auto adjusting depending on proximity to start or ending points, also using opacity. That's an interesting option. 

Why don't you do both? Have a drawable checkbox. If it's not checked we get the instant straight slope. If checked it is drawable.

**Comment by TokisanGames** [comment]
Try the height brush with low opacity and you'll see it fills in more gradually than when it is 100%.

**Comment by niceandgoodonline** [comment]
>     1. Slope when applying textures and color, painting only on flat surfaces or only on slopes.

Did a quick walk over some of the header files -- I think [this](https://github.com/TokisanGames/Terrain3D/blob/65f36b1d11e70e42e10c5b97c33ee4251c5df260/src/terrain_3d_editor.cpp#L224C13-L224C13) `case` would be the spot to add logic which restricts painting based on slope? Coupled with expanding the brush data definition [here](https://github.com/TokisanGames/Terrain3D/blob/65f36b1d11e70e42e10c5b97c33ee4251c5df260/src/terrain_3d_editor.h#L84) to include some slope-restricted-painting parameters? (and producing some editor UI stuff for end users)

(Confirming my understanding before attempting a PR)

Looking at the current issues in the 9.x and 1.0 roadmap, only[ GPU Painting](https://github.com/TokisanGames/Terrain3D/issues/174) pops out to me as a coupled feature. Would GPU painting introduce breaking changes in `_operate_map()` potentially?

**Comment by TokisanGames** [comment]
I have separated the two issues. Let's keep the discussion on sculpting a slope here. Painting based on slope has been moved to #282. @niceandgoodonline if you move your comment over there, I'll answer it.

**Comment by TokisanGames** [comment]
Fixed by #297
